/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  cpw.mods.fml.common.registry.EntityRegistry
 */
package hedaox.ninjinentities.entities;

import cpw.mods.fml.common.registry.EntityRegistry;
import hedaox.ninjinentities.entities.DAIMA.EntityDAIMAGoku;
import hedaox.ninjinentities.entities.DAIMA.EntityDAIMAGokuSsj;
import hedaox.ninjinentities.entities.DAIMA.EntityDAIMAGokuSsj2;
import hedaox.ninjinentities.entities.DAIMA.EntityDAIMAGokuSsj3;
import hedaox.ninjinentities.entities.DAIMA.EntityDAIMAGokuSsj4;
import hedaox.ninjinentities.entities.DAIMA.EntityDAIMAMajinDuu;
import hedaox.ninjinentities.entities.DAIMA.EntityDAIMAMajinDuuSsj3;
import hedaox.ninjinentities.entities.DAIMA.EntityDAIMAMajinKuu;
import hedaox.ninjinentities.entities.DAIMA.EntityDAIMAPorunga;
import hedaox.ninjinentities.entities.DAIMA.EntityDAIMAVegetaSsj3;
import hedaox.ninjinentities.entities.DAIMA.EntityGomahThirdEye;
import hedaox.ninjinentities.entities.DAIMA.EntityGomahThirdEyeGigantic;
import hedaox.ninjinentities.entities.DAIMA.EntityKaioshinChild;
import hedaox.ninjinentities.entities.DAIMA.EntityTamagami_1;
import hedaox.ninjinentities.entities.DAIMA.EntityTamagami_2;
import hedaox.ninjinentities.entities.DAIMA.EntityTamagami_3;
import hedaox.ninjinentities.entities.DB.EntityChiaotzu1;
import hedaox.ninjinentities.entities.DB.EntityCyborgTaopaipai;
import hedaox.ninjinentities.entities.DB.EntityGokuKid1;
import hedaox.ninjinentities.entities.DB.EntityGokuKid2;
import hedaox.ninjinentities.entities.DB.EntityKrillinKid1;
import hedaox.ninjinentities.entities.DB.EntityKrillinKid2;
import hedaox.ninjinentities.entities.DB.EntityOozaru;
import hedaox.ninjinentities.entities.DB.EntityPiccoloDaimaoOld;
import hedaox.ninjinentities.entities.DB.EntityPiccoloDaimaoYoung;
import hedaox.ninjinentities.entities.DB.EntityPiccoloDaimaoYoung2;
import hedaox.ninjinentities.entities.DB.EntityRoshi;
import hedaox.ninjinentities.entities.DB.EntityRoshiBuff;
import hedaox.ninjinentities.entities.DB.EntityYamcha1;
import hedaox.ninjinentities.entities.DBAF.EntityGokuSsj5;
import hedaox.ninjinentities.entities.DBAF.EntityXicor;
import hedaox.ninjinentities.entities.DBAF.EntityXicorSsj;
import hedaox.ninjinentities.entities.DBGT.Entity2Stars;
import hedaox.ninjinentities.entities.DBGT.Entity3Stars;
import hedaox.ninjinentities.entities.DBGT.Entity4Stars;
import hedaox.ninjinentities.entities.DBGT.Entity4StarsFullPower;
import hedaox.ninjinentities.entities.DBGT.Entity5Stars;
import hedaox.ninjinentities.entities.DBGT.Entity5StarsFullPower;
import hedaox.ninjinentities.entities.DBGT.Entity6Stars;
import hedaox.ninjinentities.entities.DBGT.Entity6StarsTrueform;
import hedaox.ninjinentities.entities.DBGT.Entity7Stars;
import hedaox.ninjinentities.entities.DBGT.Entity7StarsPan;
import hedaox.ninjinentities.entities.DBGT.Entity7StarsTrue;
import hedaox.ninjinentities.entities.DBGT.EntityBb;
import hedaox.ninjinentities.entities.DBGT.EntityBb2;
import hedaox.ninjinentities.entities.DBGT.EntityBbGoldOozaru;
import hedaox.ninjinentities.entities.DBGT.EntityBbssj;
import hedaox.ninjinentities.entities.DBGT.EntityBbssj2;
import hedaox.ninjinentities.entities.DBGT.EntityDragon;
import hedaox.ninjinentities.entities.DBGT.EntityGTgoku;
import hedaox.ninjinentities.entities.DBGT.EntityGTgokuChild;
import hedaox.ninjinentities.entities.DBGT.EntityGTgokuSsj;
import hedaox.ninjinentities.entities.DBGT.EntityGTgokuSsj2;
import hedaox.ninjinentities.entities.DBGT.EntityGTgokuSsj2Child;
import hedaox.ninjinentities.entities.DBGT.EntityGTgokuSsj3;
import hedaox.ninjinentities.entities.DBGT.EntityGTgokuSsj3Child;
import hedaox.ninjinentities.entities.DBGT.EntityGTgokuSsjChild;
import hedaox.ninjinentities.entities.DBGT.EntityGTvegeta;
import hedaox.ninjinentities.entities.DBGT.EntityGTvegeta2;
import hedaox.ninjinentities.entities.DBGT.EntityGTvegeta2Ssj;
import hedaox.ninjinentities.entities.DBGT.EntityGTvegeta2Ssj2;
import hedaox.ninjinentities.entities.DBGT.EntityGTvegetaSsj;
import hedaox.ninjinentities.entities.DBGT.EntityGTvegetaSsj2;
import hedaox.ninjinentities.entities.DBGT.EntityGokuSsj4;
import hedaox.ninjinentities.entities.DBGT.EntityGoldOozaru;
import hedaox.ninjinentities.entities.DBGT.EntityLedgic;
import hedaox.ninjinentities.entities.DBGT.EntitySuper17;
import hedaox.ninjinentities.entities.DBGT.EntityVegetaSsj4;
import hedaox.ninjinentities.entities.DBGT.Entityhetilierde;
import hedaox.ninjinentities.entities.DBGT.Entitylierde;
import hedaox.ninjinentities.entities.DBGT.Entitylude;
import hedaox.ninjinentities.entities.DBGT.EntityludeFullPower;
import hedaox.ninjinentities.entities.DBGT.Entityomega;
import hedaox.ninjinentities.entities.DBGT.Entityomega2;
import hedaox.ninjinentities.entities.DBS.EntityBergamoNinjin;
import hedaox.ninjinentities.entities.DBS.EntityBlackFrieza;
import hedaox.ninjinentities.entities.DBS.EntityCellmax;
import hedaox.ninjinentities.entities.DBS.EntityCocotteNinjin;
import hedaox.ninjinentities.entities.DBS.EntityGamma1;
import hedaox.ninjinentities.entities.DBS.EntityGamma2;
import hedaox.ninjinentities.entities.DBS.EntityGogeta;
import hedaox.ninjinentities.entities.DBS.EntityGogetaSsj;
import hedaox.ninjinentities.entities.DBS.EntityGogetaSsjb;
import hedaox.ninjinentities.entities.DBS.EntityGohanBeast;
import hedaox.ninjinentities.entities.DBS.EntityGokuBlackR;
import hedaox.ninjinentities.entities.DBS.EntityGokuBlackSsj;
import hedaox.ninjinentities.entities.DBS.EntityGokuSsjb;
import hedaox.ninjinentities.entities.DBS.EntityGokuSsjbk;
import hedaox.ninjinentities.entities.DBS.EntityGokuSsjg;
import hedaox.ninjinentities.entities.DBS.EntityGokuSuper;
import hedaox.ninjinentities.entities.DBS.EntityGokuSuperSsj;
import hedaox.ninjinentities.entities.DBS.EntityGokuSuperSsjb;
import hedaox.ninjinentities.entities.DBS.EntityGokuUI;
import hedaox.ninjinentities.entities.DBS.EntityGokuUIM;
import hedaox.ninjinentities.entities.DBS.EntityHit;
import hedaox.ninjinentities.entities.DBS.EntityJs;
import hedaox.ninjinentities.entities.DBS.EntityKahseralNinjin;
import hedaox.ninjinentities.entities.DBS.EntityKettle;
import hedaox.ninjinentities.entities.DBS.EntityKnsi;
import hedaox.ninjinentities.entities.DBS.EntityLavenderNinjin;
import hedaox.ninjinentities.entities.DBS.EntityMara;
import hedaox.ninjinentities.entities.DBS.EntityMara_Fusion;
import hedaox.ninjinentities.entities.DBS.EntityMara_Young;
import hedaox.ninjinentities.entities.DBS.EntityMonaka;
import hedaox.ninjinentities.entities.DBS.EntityPiccolo2;
import hedaox.ninjinentities.entities.DBS.EntityPiccolo3;
import hedaox.ninjinentities.entities.DBS.EntityPiccolo4;
import hedaox.ninjinentities.entities.DBS.EntityPiccolo5;
import hedaox.ninjinentities.entities.DBS.EntityPilina;
import hedaox.ninjinentities.entities.DBS.EntitySaonel;
import hedaox.ninjinentities.entities.DBS.EntityTrunksFuturSuper;
import hedaox.ninjinentities.entities.DBS.EntityTrunksFuturSuperSsj;
import hedaox.ninjinentities.entities.DBS.EntityTrunksFuturSuperSsj2;
import hedaox.ninjinentities.entities.DBS.EntityTrunksFuturSuperSsjG3;
import hedaox.ninjinentities.entities.DBS.EntityTrunksFuturSuperSsjRage;
import hedaox.ninjinentities.entities.DBS.EntityTupper;
import hedaox.ninjinentities.entities.DBS.EntityVegetaCopy;
import hedaox.ninjinentities.entities.DBS.EntityVegetaCopyBlue;
import hedaox.ninjinentities.entities.DBS.EntityVegetaSsjb;
import hedaox.ninjinentities.entities.DBS.EntityVegetaSsjbe;
import hedaox.ninjinentities.entities.DBS.EntityVegetaSsjg;
import hedaox.ninjinentities.entities.DBS.EntityVegetaSuper;
import hedaox.ninjinentities.entities.DBS.EntityVegetaSuperSsj;
import hedaox.ninjinentities.entities.DBS.EntityVegetaSuperSsjb;
import hedaox.ninjinentities.entities.DBS.EntityVegetaZw;
import hedaox.ninjinentities.entities.DBS.EntityVegetoSsjb;
import hedaox.ninjinentities.entities.DBS.EntityVewon;
import hedaox.ninjinentities.entities.DBS.EntityWhis;
import hedaox.ninjinentities.entities.DBS.EntityZoire;
import hedaox.ninjinentities.entities.DBS.Entityglnl;
import hedaox.ninjinentities.entities.DBZ.EntityCell4Ninjin;
import hedaox.ninjinentities.entities.DBZ.EntityChiaotzu2;
import hedaox.ninjinentities.entities.DBZ.EntityEldKaioshin;
import hedaox.ninjinentities.entities.DBZ.EntityFreeza5Damaged;
import hedaox.ninjinentities.entities.DBZ.EntityFreeza6Damaged;
import hedaox.ninjinentities.entities.DBZ.EntityFutureGohan;
import hedaox.ninjinentities.entities.DBZ.EntityFutureGohan2;
import hedaox.ninjinentities.entities.DBZ.EntityFutureGohan2Ssj;
import hedaox.ninjinentities.entities.DBZ.EntityFutureGohanSsj;
import hedaox.ninjinentities.entities.DBZ.EntityGinyuGoku;
import hedaox.ninjinentities.entities.DBZ.EntityGohanAdult;
import hedaox.ninjinentities.entities.DBZ.EntityGohanAdultSsj;
import hedaox.ninjinentities.entities.DBZ.EntityGohanAdultSsj2;
import hedaox.ninjinentities.entities.DBZ.EntityGohanKid1;
import hedaox.ninjinentities.entities.DBZ.EntityGohanKid2;
import hedaox.ninjinentities.entities.DBZ.EntityGohanKid3;
import hedaox.ninjinentities.entities.DBZ.EntityGohanKidArmor;
import hedaox.ninjinentities.entities.DBZ.EntityGohanTeen;
import hedaox.ninjinentities.entities.DBZ.EntityGohanTeenArmor;
import hedaox.ninjinentities.entities.DBZ.EntityGohanTeenArmorSsj;
import hedaox.ninjinentities.entities.DBZ.EntityGohanTeenSsj;
import hedaox.ninjinentities.entities.DBZ.EntityGohanTeenSsj2;
import hedaox.ninjinentities.entities.DBZ.EntityGohanUltimate;
import hedaox.ninjinentities.entities.DBZ.EntityGoku1;
import hedaox.ninjinentities.entities.DBZ.EntityGoku2;
import hedaox.ninjinentities.entities.DBZ.EntityGoku2Kaioken;
import hedaox.ninjinentities.entities.DBZ.EntityGokuArmor;
import hedaox.ninjinentities.entities.DBZ.EntityGokuArmorSsj;
import hedaox.ninjinentities.entities.DBZ.EntityGokuSsj;
import hedaox.ninjinentities.entities.DBZ.EntityGokuSsj2;
import hedaox.ninjinentities.entities.DBZ.EntityGokuSsj3;
import hedaox.ninjinentities.entities.DBZ.EntityGokuYardrat;
import hedaox.ninjinentities.entities.DBZ.EntityGokuYardratSsj;
import hedaox.ninjinentities.entities.DBZ.EntityGokunoweight;
import hedaox.ninjinentities.entities.DBZ.EntityGoten;
import hedaox.ninjinentities.entities.DBZ.EntityGotenSsj;
import hedaox.ninjinentities.entities.DBZ.EntityGotenks;
import hedaox.ninjinentities.entities.DBZ.EntityGotenksSsj;
import hedaox.ninjinentities.entities.DBZ.EntityGotenksSsj3;
import hedaox.ninjinentities.entities.DBZ.EntityHercule;
import hedaox.ninjinentities.entities.DBZ.EntityKaioshin;
import hedaox.ninjinentities.entities.DBZ.EntityKibito;
import hedaox.ninjinentities.entities.DBZ.EntityKrillin1;
import hedaox.ninjinentities.entities.DBZ.EntityKrillin2;
import hedaox.ninjinentities.entities.DBZ.EntityMajinSoldier1;
import hedaox.ninjinentities.entities.DBZ.EntityMajinSoldier2;
import hedaox.ninjinentities.entities.DBZ.EntityMasterBaba;
import hedaox.ninjinentities.entities.DBZ.EntityNail;
import hedaox.ninjinentities.entities.DBZ.EntityNappa;
import hedaox.ninjinentities.entities.DBZ.EntityNappaDamaged;
import hedaox.ninjinentities.entities.DBZ.EntityPiccolo;
import hedaox.ninjinentities.entities.DBZ.EntityPiccoloInjury;
import hedaox.ninjinentities.entities.DBZ.EntityPikkon;
import hedaox.ninjinentities.entities.DBZ.EntityPorungaNinjin;
import hedaox.ninjinentities.entities.DBZ.EntityRaditz;
import hedaox.ninjinentities.entities.DBZ.EntityRecoomeDamaged;
import hedaox.ninjinentities.entities.DBZ.EntitySpopovich;
import hedaox.ninjinentities.entities.DBZ.EntityTrunksArmor;
import hedaox.ninjinentities.entities.DBZ.EntityTrunksArmorSsj;
import hedaox.ninjinentities.entities.DBZ.EntityTrunksArmorSsjG2;
import hedaox.ninjinentities.entities.DBZ.EntityTrunksArmorSsjG3;
import hedaox.ninjinentities.entities.DBZ.EntityTrunksFutur;
import hedaox.ninjinentities.entities.DBZ.EntityTrunksFuturSsj;
import hedaox.ninjinentities.entities.DBZ.EntityTrunksKid;
import hedaox.ninjinentities.entities.DBZ.EntityTrunksKidSsj;
import hedaox.ninjinentities.entities.DBZ.EntityVegeta0;
import hedaox.ninjinentities.entities.DBZ.EntityVegeta0Damaged;
import hedaox.ninjinentities.entities.DBZ.EntityVegeta1;
import hedaox.ninjinentities.entities.DBZ.EntityVegeta2;
import hedaox.ninjinentities.entities.DBZ.EntityVegeta2Ssj;
import hedaox.ninjinentities.entities.DBZ.EntityVegeta2Ssj2;
import hedaox.ninjinentities.entities.DBZ.EntityVegeta3;
import hedaox.ninjinentities.entities.DBZ.EntityVegetaMajin;
import hedaox.ninjinentities.entities.DBZ.EntityVegetaOozaru;
import hedaox.ninjinentities.entities.DBZ.EntityVegetaSsj;
import hedaox.ninjinentities.entities.DBZ.EntityVegetaSsjG2;
import hedaox.ninjinentities.entities.DBZ.EntityVegeto;
import hedaox.ninjinentities.entities.DBZ.EntityVegetoSsj;
import hedaox.ninjinentities.entities.DBZ.EntityYamcha2;
import hedaox.ninjinentities.entities.DBZ.EntityYamcha3;
import hedaox.ninjinentities.entities.DBZ.EntityYamu;
import hedaox.ninjinentities.entities.IF.EntityBlockGohanUltimate;
import hedaox.ninjinentities.entities.Movies.EntityAbo;
import hedaox.ninjinentities.entities.Movies.EntityAka;
import hedaox.ninjinentities.entities.Movies.EntityAmond;
import hedaox.ninjinentities.entities.Movies.EntityAndroid13;
import hedaox.ninjinentities.entities.Movies.EntityAndroid13Super;
import hedaox.ninjinentities.entities.Movies.EntityAndroid14;
import hedaox.ninjinentities.entities.Movies.EntityAndroid15;
import hedaox.ninjinentities.entities.Movies.EntityAngila;
import hedaox.ninjinentities.entities.Movies.EntityAngol;
import hedaox.ninjinentities.entities.Movies.EntityArbee;
import hedaox.ninjinentities.entities.Movies.EntityBdkNinjin;
import hedaox.ninjinentities.entities.Movies.EntityBdkssjNinjin;
import hedaox.ninjinentities.entities.Movies.EntityBido;
import hedaox.ninjinentities.entities.Movies.EntityBioWarrior1;
import hedaox.ninjinentities.entities.Movies.EntityBioWarrior2;
import hedaox.ninjinentities.entities.Movies.EntityBioWarrior3;
import hedaox.ninjinentities.entities.Movies.EntityBioWarrior4;
import hedaox.ninjinentities.entities.Movies.EntityBioWarrior5;
import hedaox.ninjinentities.entities.Movies.EntityBioWarrior6;
import hedaox.ninjinentities.entities.Movies.EntityBiomen;
import hedaox.ninjinentities.entities.Movies.EntityBojack;
import hedaox.ninjinentities.entities.Movies.EntityBojackSuper;
import hedaox.ninjinentities.entities.Movies.EntityBrolyZ2Ssj;
import hedaox.ninjinentities.entities.Movies.EntityBrolyZBase;
import hedaox.ninjinentities.entities.Movies.EntityBrolyZBio;
import hedaox.ninjinentities.entities.Movies.EntityBrolyZLSsj;
import hedaox.ninjinentities.entities.Movies.EntityBrolyZSsj;
import hedaox.ninjinentities.entities.Movies.EntityBudo;
import hedaox.ninjinentities.entities.Movies.EntityBujin;
import hedaox.ninjinentities.entities.Movies.EntityCacao;
import hedaox.ninjinentities.entities.Movies.EntityChilled;
import hedaox.ninjinentities.entities.Movies.EntityCooler;
import hedaox.ninjinentities.entities.Movies.EntityCoolerFifthForm;
import hedaox.ninjinentities.entities.Movies.EntityCoolerMetal;
import hedaox.ninjinentities.entities.Movies.EntityCoolerMetalTrueForm;
import hedaox.ninjinentities.entities.Movies.EntityCyclopianGuard;
import hedaox.ninjinentities.entities.Movies.EntityDaiz;
import hedaox.ninjinentities.entities.Movies.EntityDore;
import hedaox.ninjinentities.entities.Movies.EntityDrWheelo;
import hedaox.ninjinentities.entities.Movies.EntityEbifurya;
import hedaox.ninjinentities.entities.Movies.EntityGarlicJr;
import hedaox.ninjinentities.entities.Movies.EntityGarlicJrSuper;
import hedaox.ninjinentities.entities.Movies.EntityGinger;
import hedaox.ninjinentities.entities.Movies.EntityGure;
import hedaox.ninjinentities.entities.Movies.EntityHatchiyack;
import hedaox.ninjinentities.entities.Movies.EntityHatchiyackGiant;
import hedaox.ninjinentities.entities.Movies.EntityHatchiyackSuper;
import hedaox.ninjinentities.entities.Movies.EntityHirudegarnBottom;
import hedaox.ninjinentities.entities.Movies.EntityHirudegarnPost;
import hedaox.ninjinentities.entities.Movies.EntityHirudegarnPre;
import hedaox.ninjinentities.entities.Movies.EntityHirudegarnUpper;
import hedaox.ninjinentities.entities.Movies.EntityHoi;
import hedaox.ninjinentities.entities.Movies.EntityJanemba;
import hedaox.ninjinentities.entities.Movies.EntityJanembaSuper;
import hedaox.ninjinentities.entities.Movies.EntityJiku;
import hedaox.ninjinentities.entities.Movies.EntityKado;
import hedaox.ninjinentities.entities.Movies.EntityKawazu;
import hedaox.ninjinentities.entities.Movies.EntityKinkarn;
import hedaox.ninjinentities.entities.Movies.EntityKishime;
import hedaox.ninjinentities.entities.Movies.EntityKogu;
import hedaox.ninjinentities.entities.Movies.EntityKoguSuper;
import hedaox.ninjinentities.entities.Movies.EntityLakasei;
import hedaox.ninjinentities.entities.Movies.EntityMedamatcha;
import hedaox.ninjinentities.entities.Movies.EntityMedamatchaClone;
import hedaox.ninjinentities.entities.Movies.EntityMisokatsun;
import hedaox.ninjinentities.entities.Movies.EntityMoah;
import hedaox.ninjinentities.entities.Movies.EntityNeiz;
import hedaox.ninjinentities.entities.Movies.EntityNicky;
import hedaox.ninjinentities.entities.Movies.EntityParagus;
import hedaox.ninjinentities.entities.Movies.EntityParagusSoldier;
import hedaox.ninjinentities.entities.Movies.EntityPonkarn;
import hedaox.ninjinentities.entities.Movies.EntityRasin;
import hedaox.ninjinentities.entities.Movies.EntitySalza;
import hedaox.ninjinentities.entities.Movies.EntitySansho;
import hedaox.ninjinentities.entities.Movies.EntitySkud;
import hedaox.ninjinentities.entities.Movies.EntitySlugGiant;
import hedaox.ninjinentities.entities.Movies.EntitySlugOld;
import hedaox.ninjinentities.entities.Movies.EntitySlugSoldier;
import hedaox.ninjinentities.entities.Movies.EntitySlugYoung;
import hedaox.ninjinentities.entities.Movies.EntityTurles1;
import hedaox.ninjinentities.entities.Movies.EntityTurles2;
import hedaox.ninjinentities.entities.Movies.EntityTurles3;
import hedaox.ninjinentities.entities.Movies.EntityWings;
import hedaox.ninjinentities.entities.Movies.EntityZangya;
import hedaox.ninjinentities.entities.Movies.EntityZeeun;
import hedaox.ninjinentities.entities.ZENO.EntityBdkSsj4;
import hedaox.ninjinentities.entities.ZENO.EntityBlockGoku;
import hedaox.ninjinentities.entities.ZENO.EntityBlockGokuSsjR;
import hedaox.ninjinentities.entities.ZENO.EntityBlockGokuSsjR3;
import hedaox.ninjinentities.entities.ZENO.EntityBzGokuSsj;
import hedaox.ninjinentities.entities.ZENO.EntityFu;
import hedaox.ninjinentities.entities.ZENO.EntityGoldCooler;
import hedaox.ninjinentities.entities.ZENO.EntityGoldCoolerFifthForm;
import hedaox.ninjinentities.entities.ZENO.EntityGoldCoolerMetal;
import hedaox.ninjinentities.entities.ZENO.EntityKanba;
import hedaox.ninjinentities.entities.ZENO.EntityKanbaSsj2;
import hedaox.ninjinentities.entities.ZENO.EntityKanbaSsj3;
import hedaox.ninjinentities.entities.ZENO.EntityKanbaSsjoozaru;
import hedaox.ninjinentities.entities.ZENO.EntityKanbassj;
import hedaox.ninjinentities.entities.doujin.EntityBdkssj3Ninjin;
import hedaox.ninjinentities.entities.doujin.EntityBdkssjb3Ninjin;
import hedaox.ninjinentities.entities.doujin.EntityBdkssjbNinjin;
import hedaox.ninjinentities.entities.doujin.EntityBrolyZLSsj3;
import hedaox.ninjinentities.entities.doujin.EntityCellperfectmax;
import hedaox.ninjinentities.entities.doujin.EntityGogetaSsj2;
import hedaox.ninjinentities.entities.doujin.EntityGogetaSsj3;
import hedaox.ninjinentities.entities.doujin.EntityGogetaUi;
import hedaox.ninjinentities.entities.doujin.EntityGogetaUw;
import hedaox.ninjinentities.entities.doujin.EntityGoldcellNinjin;
import hedaox.ninjinentities.entities.doujin.EntityVegetoSsj2;
import hedaox.ninjinentities.entities.doujin.EntityVegetoSsj3;
import hedaox.ninjinentities.entities.doujin.EntityVegetoUi;
import hedaox.ninjinentities.entities.doujin.EntityVegetoUw;
import hedaox.ninjinentities.entities.doujin.EntityZsCoolerFifthForm;
import hedaox.ninjinentities.entities.doujin.EntityZsfls;

public class NinjinEntities {
    private static int entityId = 0;

    public static void init() {
        NinjinEntities.createEntity(EntityMasterBaba.class, 64, "masterBaba");
        NinjinEntities.createEntity(EntityHercule.class, 64, "hercule");
        NinjinEntities.createEntity(EntityGohanAdult.class, 64, "gohanAdult");
        NinjinEntities.createEntity(EntityGohanAdultSsj.class, 64, "gohanAdultSsj");
        NinjinEntities.createEntity(EntityGohanAdultSsj2.class, 64, "gohanAdultSsj2");
        NinjinEntities.createEntity(EntityGohanKid1.class, 64, "gohanKid1");
        NinjinEntities.createEntity(EntityGohanKid2.class, 64, "gohanKid2");
        NinjinEntities.createEntity(EntityGohanKid3.class, 64, "gohanKid3");
        NinjinEntities.createEntity(EntityGohanKidArmor.class, 64, "gohanKidArmor");
        NinjinEntities.createEntity(EntityGohanTeen.class, 64, "gohanTeen");
        NinjinEntities.createEntity(EntityGohanTeenArmor.class, 64, "gohanTeenArmor");
        NinjinEntities.createEntity(EntityGohanTeenArmorSsj.class, 64, "gohanTeenArmorSsj");
        NinjinEntities.createEntity(EntityGohanTeenSsj.class, 64, "gohanTeenSsj");
        NinjinEntities.createEntity(EntityGohanTeenSsj2.class, 64, "gohanTeenSsj2");
        NinjinEntities.createEntity(EntityFutureGohan.class, 64, "FutureGohan");
        NinjinEntities.createEntity(EntityFutureGohan2.class, 64, "FutureGohan2");
        NinjinEntities.createEntity(EntityFutureGohanSsj.class, 64, "FutureGohanSsj");
        NinjinEntities.createEntity(EntityFutureGohan2Ssj.class, 64, "FutureGohan2Ssj");
        NinjinEntities.createEntity(EntityGohanUltimate.class, 64, "gohanUltimate");
        NinjinEntities.createEntity(EntityGohanBeast.class, 64, "gohanBeast");
        NinjinEntities.createEntity(EntityGokuKid1.class, 64, "gokuKid1");
        NinjinEntities.createEntity(EntityGokuKid2.class, 64, "gokuKid2");
        NinjinEntities.createEntity(EntityGoku1.class, 64, "goku1");
        NinjinEntities.createEntity(EntityGoku2Kaioken.class, 64, "goku2Kaioken");
        NinjinEntities.createEntity(EntityGoku2.class, 64, "goku2");
        NinjinEntities.createEntity(EntityGokuArmor.class, 64, "gokuArmor");
        NinjinEntities.createEntity(EntityGokuArmorSsj.class, 64, "gokuArmorSsj");
        NinjinEntities.createEntity(EntityGokunoweight.class, 64, "gokunoweight");
        NinjinEntities.createEntity(EntityGokuSsj.class, 64, "gokuSsj");
        NinjinEntities.createEntity(EntityGokuSsj2.class, 64, "gokuSsj2");
        NinjinEntities.createEntity(EntityGokuSsj3.class, 64, "gokuSsj3");
        NinjinEntities.createEntity(EntityGokuSsj5.class, 64, "gokuSsj5");
        NinjinEntities.createEntity(EntityGokuSsjg.class, 64, "gokuSsjg");
        NinjinEntities.createEntity(EntityGokuSsjb.class, 64, "gokuSsjb");
        NinjinEntities.createEntity(EntityGokuSsjbk.class, 64, "gokuSsjbk");
        NinjinEntities.createEntity(EntityGokuSuper.class, 64, "gokuSuper");
        NinjinEntities.createEntity(EntityGokuSuperSsj.class, 64, "gokuSuperSsj");
        NinjinEntities.createEntity(EntityGokuSuperSsjb.class, 64, "gokuSuperSsjb");
        NinjinEntities.createEntity(EntityGokuUI.class, 64, "gokuUi");
        NinjinEntities.createEntity(EntityGokuUIM.class, 64, "gokuUiM");
        NinjinEntities.createEntity(EntityGokuYardrat.class, 64, "gokuYardrat");
        NinjinEntities.createEntity(EntityGokuYardratSsj.class, 64, "gokuYardratSsj");
        NinjinEntities.createEntity(EntityGTgoku.class, 64, "GTgoku");
        NinjinEntities.createEntity(EntityGTgokuSsj.class, 64, "GTgokuSsj");
        NinjinEntities.createEntity(EntityGTgokuSsj2.class, 64, "GTgokuSsj2");
        NinjinEntities.createEntity(EntityGTgokuSsj3.class, 64, "GTgokuSsj3");
        NinjinEntities.createEntity(EntityGTgokuChild.class, 64, "GTgokuChild");
        NinjinEntities.createEntity(EntityGTgokuSsjChild.class, 64, "GTgokudSsjChil");
        NinjinEntities.createEntity(EntityGTgokuSsj2Child.class, 64, "GTgokuSsj2Child");
        NinjinEntities.createEntity(EntityGTgokuSsj3Child.class, 64, "GTgokuSsj3Child");
        NinjinEntities.createEntity(EntityGokuSsj4.class, 64, "gokuSsj4");
        NinjinEntities.createEntity(EntityGoten.class, 64, "goten");
        NinjinEntities.createEntity(EntityGotenSsj.class, 64, "gotenSsj");
        NinjinEntities.createEntity(EntityGotenks.class, 64, "gotenks");
        NinjinEntities.createEntity(EntityGotenksSsj.class, 64, "gotenksSsj");
        NinjinEntities.createEntity(EntityGotenksSsj3.class, 64, "gotenksSsj3");
        NinjinEntities.createEntity(EntityKrillin1.class, 64, "krillin1");
        NinjinEntities.createEntity(EntityKrillin2.class, 64, "krillin2");
        NinjinEntities.createEntity(EntityKrillinKid1.class, 64, "krillinKid1");
        NinjinEntities.createEntity(EntityKrillinKid2.class, 64, "krillinKid2");
        NinjinEntities.createEntity(Entityglnl.class, 64, "glnl");
        NinjinEntities.createEntity(EntityKanba.class, 64, "kanba");
        NinjinEntities.createEntity(EntityKanbassj.class, 64, "kanbassj");
        NinjinEntities.createEntity(EntityKanbaSsj2.class, 64, "kanbassj2");
        NinjinEntities.createEntity(EntityKanbaSsj3.class, 64, "kanbassj3");
        NinjinEntities.createEntity(EntityKanbaSsjoozaru.class, 64, "kanbassjoozaru");
        NinjinEntities.createEntity(EntityChiaotzu1.class, 64, "chiaotzu1");
        NinjinEntities.createEntity(EntityChiaotzu2.class, 64, "chiaotzu2");
        NinjinEntities.createEntity(EntityYamcha1.class, 64, "yamcha1");
        NinjinEntities.createEntity(EntityYamcha2.class, 64, "yamcha2");
        NinjinEntities.createEntity(EntityYamcha3.class, 64, "yamcha3");
        NinjinEntities.createEntity(EntityPiccolo.class, 64, "piccolo");
        NinjinEntities.createEntity(EntityPiccoloInjury.class, 64, "PiccoloInjury");
        NinjinEntities.createEntity(EntityOozaru.class, 64, "oozaru");
        NinjinEntities.createEntity(EntityRoshi.class, 64, "roshi");
        NinjinEntities.createEntity(EntityRoshiBuff.class, 64, "roshiBuff");
        NinjinEntities.createEntity(EntityTrunksArmor.class, 64, "trunksArmor");
        NinjinEntities.createEntity(EntityTrunksArmorSsj.class, 64, "trunksArmorSsj");
        NinjinEntities.createEntity(EntityTrunksArmorSsjG2.class, 64, "trunksArmorSsjG2");
        NinjinEntities.createEntity(EntityTrunksArmorSsjG3.class, 64, "trunksArmorSsjG3");
        NinjinEntities.createEntity(EntityTrunksFutur.class, 64, "trunksFutur");
        NinjinEntities.createEntity(EntityTrunksFuturSsj.class, 64, "trunksFuturSsj");
        NinjinEntities.createEntity(EntityTrunksFuturSuper.class, 64, "trunksFuturSuper");
        NinjinEntities.createEntity(EntityTrunksFuturSuperSsj.class, 64, "trunksFuturSuperSsj");
        NinjinEntities.createEntity(EntityTrunksFuturSuperSsj2.class, 64, "trunksFuturSuperSsj2");
        NinjinEntities.createEntity(EntityTrunksFuturSuperSsjG3.class, 64, "trunksFuturSuperSsjG3");
        NinjinEntities.createEntity(EntityTrunksFuturSuperSsjRage.class, 64, "trunksFuturSuperSsjRage");
        NinjinEntities.createEntity(EntityTrunksKid.class, 64, "trunksKid");
        NinjinEntities.createEntity(EntityTrunksKidSsj.class, 64, "trunksKidSsj");
        NinjinEntities.createEntity(EntityVegeto.class, 64, "vegeto");
        NinjinEntities.createEntity(EntityVegetoSsj2.class, 64, "vegetoSsj2");
        NinjinEntities.createEntity(EntityVegetoSsj3.class, 64, "vegetoSsj3");
        NinjinEntities.createEntity(EntityVegetoSsj.class, 64, "vegetoSsj");
        NinjinEntities.createEntity(EntityVegetoSsjb.class, 64, "vegetoSsjb");
        NinjinEntities.createEntity(EntityVegetoUi.class, 64, "vegetoUi");
        NinjinEntities.createEntity(EntityVegetoUw.class, 64, "vegetoUw");
        NinjinEntities.createEntity(EntityGogeta.class, 64, "gogeta");
        NinjinEntities.createEntity(EntityGogetaSsj.class, 64, "gogetaSsj");
        NinjinEntities.createEntity(EntityGogetaSsj2.class, 64, "gogetaSsj2");
        NinjinEntities.createEntity(EntityGogetaSsj3.class, 64, "gogetaSsj3");
        NinjinEntities.createEntity(EntityGogetaSsjb.class, 64, "gogetaSsjb");
        NinjinEntities.createEntity(EntityGogetaUi.class, 64, "gogetaUi");
        NinjinEntities.createEntity(EntityGogetaUw.class, 64, "gogetaUw");
        NinjinEntities.createEntity(EntityVegeta0.class, 64, "vegeta0");
        NinjinEntities.createEntity(EntityVegeta0Damaged.class, 64, "vegeta0Damaged");
        NinjinEntities.createEntity(EntityVegeta1.class, 64, "vegeta");
        NinjinEntities.createEntity(EntityVegeta3.class, 64, "vegeta3");
        NinjinEntities.createEntity(EntityVegetaSsj.class, 64, "vegetaSsj");
        NinjinEntities.createEntity(EntityVegetaSsjG2.class, 64, "vegetaSsjG2");
        NinjinEntities.createEntity(EntityVegeta2.class, 64, "vegeta2");
        NinjinEntities.createEntity(EntityVegeta2Ssj.class, 64, "vegeta2Ssj");
        NinjinEntities.createEntity(EntityVegeta2Ssj2.class, 64, "vegeta2Ssj2");
        NinjinEntities.createEntity(EntityVegetaSsjg.class, 64, "vegetaSsjg");
        NinjinEntities.createEntity(EntityVegetaSsjb.class, 64, "vegetaSsjb");
        NinjinEntities.createEntity(EntityVegetaSsjbe.class, 64, "vegetaSsjbe");
        NinjinEntities.createEntity(EntityVegetaMajin.class, 64, "vegetaMajin");
        NinjinEntities.createEntity(EntityVegetaOozaru.class, 64, "vegetaOozaru");
        NinjinEntities.createEntity(EntityVegetaCopy.class, 64, "vegetaCopy");
        NinjinEntities.createEntity(EntityVegetaCopyBlue.class, 64, "vegetaBlueCopy");
        NinjinEntities.createEntity(EntityVegetaSuper.class, 64, "vegetaSuper");
        NinjinEntities.createEntity(EntityVegetaSuperSsj.class, 64, "vegetaSuperSsj");
        NinjinEntities.createEntity(EntityVegetaSuperSsjb.class, 64, "vegetaSuperSsjb");
        NinjinEntities.createEntity(EntityGTvegeta.class, 64, "GTvegeta");
        NinjinEntities.createEntity(EntityGTvegeta2.class, 64, "GTvegeta2");
        NinjinEntities.createEntity(EntityGTvegeta2Ssj.class, 64, "GTvegeta2Ssj");
        NinjinEntities.createEntity(EntityGTvegetaSsj.class, 64, "GTvegetaSsj");
        NinjinEntities.createEntity(EntityGTvegeta2Ssj2.class, 64, "GTvegeta2Ssj2");
        NinjinEntities.createEntity(EntityGTvegetaSsj2.class, 64, "GTvegetaSsj2");
        NinjinEntities.createEntity(EntityCyborgTaopaipai.class, 64, "cyborgTaopaipai");
        NinjinEntities.createEntity(EntityPiccoloDaimaoOld.class, 64, "piccoloDaimaoOld");
        NinjinEntities.createEntity(EntityPiccoloDaimaoYoung.class, 64, "piccoloDaimaoYoung");
        NinjinEntities.createEntity(EntityPiccoloDaimaoYoung2.class, 64, "piccoloDaimaoYoung2");
        NinjinEntities.createEntity(EntityHit.class, 64, "hit");
        NinjinEntities.createEntity(EntityFreeza5Damaged.class, 64, "freeza5Damaged");
        NinjinEntities.createEntity(EntityFreeza6Damaged.class, 64, "freeza6Damaged");
        NinjinEntities.createEntity(EntityMonaka.class, 64, "monaka");
        NinjinEntities.createEntity(EntityGokuBlackSsj.class, 64, "gokuBlackSsj");
        NinjinEntities.createEntity(EntityGokuBlackR.class, 64, "gokuBlackR");
        NinjinEntities.createEntity(EntityKahseralNinjin.class, 64, "kahseral");
        NinjinEntities.createEntity(EntityCocotteNinjin.class, 64, "cocotte");
        NinjinEntities.createEntity(EntityVewon.class, 64, "vewon");
        NinjinEntities.createEntity(EntityTupper.class, 64, "tupper");
        NinjinEntities.createEntity(EntityZoire.class, 64, "zoire");
        NinjinEntities.createEntity(EntityKettle.class, 64, "kettle");
        NinjinEntities.createEntity(EntityKnsi.class, 64, "knsi");
        NinjinEntities.createEntity(EntityBergamoNinjin.class, 64, "bergamo");
        NinjinEntities.createEntity(EntityLavenderNinjin.class, 64, "lavender");
        NinjinEntities.createEntity(EntityPilina.class, 64, "pilina");
        NinjinEntities.createEntity(EntitySaonel.class, 64, "saonel");
        NinjinEntities.createEntity(EntityNail.class, 64, "nail");
        NinjinEntities.createEntity(EntityGinyuGoku.class, 64, "ginyuGoku");
        NinjinEntities.createEntity(EntitySpopovich.class, 64, "spopovich");
        NinjinEntities.createEntity(EntityYamu.class, 64, "yamu");
        NinjinEntities.createEntity(EntityMajinSoldier1.class, 64, "majinSoldier1");
        NinjinEntities.createEntity(EntityMajinSoldier2.class, 64, "majinSoldier2");
        NinjinEntities.createEntity(EntityGinyuGoku.class, 64, "ginyuGoku");
        NinjinEntities.createEntity(EntityWhis.class, 64, "whis");
        NinjinEntities.createEntity(EntityRaditz.class, 64, "raditz");
        NinjinEntities.createEntity(EntityNappa.class, 64, "nappa");
        NinjinEntities.createEntity(EntityNappaDamaged.class, 64, "nappaDamaged");
        NinjinEntities.createEntity(EntityBioWarrior1.class, 64, "bioWarrior1");
        NinjinEntities.createEntity(EntityBioWarrior2.class, 64, "bioWarrior2");
        NinjinEntities.createEntity(EntityBioWarrior3.class, 64, "bioWarrior3");
        NinjinEntities.createEntity(EntityBioWarrior4.class, 64, "bioWarrior4");
        NinjinEntities.createEntity(EntityBioWarrior5.class, 64, "bioWarrior5");
        NinjinEntities.createEntity(EntityBioWarrior6.class, 64, "bioWarrior6");
        NinjinEntities.createEntity(EntityBrolyZBio.class, 64, "brolyZBio");
        NinjinEntities.createEntity(EntityBido.class, 64, "bido");
        NinjinEntities.createEntity(EntityBojack.class, 64, "bojack");
        NinjinEntities.createEntity(EntityBojackSuper.class, 64, "bojackSuper");
        NinjinEntities.createEntity(EntityBujin.class, 64, "bujin");
        NinjinEntities.createEntity(EntityKogu.class, 64, "kogu");
        NinjinEntities.createEntity(EntityKoguSuper.class, 64, "koguSuper");
        NinjinEntities.createEntity(EntityZangya.class, 64, "zangya");
        NinjinEntities.createEntity(EntityAngol.class, 64, "angol");
        NinjinEntities.createEntity(EntityBrolyZBase.class, 64, "brolyZBase");
        NinjinEntities.createEntity(EntityBrolyZLSsj.class, 64, "brolyZLSsj");
        NinjinEntities.createEntity(EntityBrolyZLSsj3.class, 64, "brolyZLSsj3");
        NinjinEntities.createEntity(EntityBrolyZSsj.class, 64, "brolyZSsj");
        NinjinEntities.createEntity(EntityBrolyZ2Ssj.class, 64, "brolyZ2Ssj");
        NinjinEntities.createEntity(EntityMoah.class, 64, "moah");
        NinjinEntities.createEntity(EntityParagus.class, 64, "paragus");
        NinjinEntities.createEntity(EntityParagusSoldier.class, 64, "paragusSoldier");
        NinjinEntities.createEntity(EntityCooler.class, 64, "cooler");
        NinjinEntities.createEntity(EntityCoolerFifthForm.class, 64, "coolerFifthForm");
        NinjinEntities.createEntity(EntityDore.class, 64, "dore");
        NinjinEntities.createEntity(EntityNeiz.class, 64, "neiz");
        NinjinEntities.createEntity(EntitySalza.class, 64, "salza");
        NinjinEntities.createEntity(EntityGarlicJr.class, 64, "garlicJr");
        NinjinEntities.createEntity(EntityGarlicJrSuper.class, 64, "garlicJrSuper");
        NinjinEntities.createEntity(EntityGinger.class, 64, "ginger");
        NinjinEntities.createEntity(EntityNicky.class, 64, "nicky");
        NinjinEntities.createEntity(EntitySansho.class, 64, "sansho");
        NinjinEntities.createEntity(EntityJanemba.class, 64, "janemba");
        NinjinEntities.createEntity(EntityJanembaSuper.class, 64, "janembaSuper");
        NinjinEntities.createEntity(EntityAngila.class, 64, "angila");
        NinjinEntities.createEntity(EntitySlugOld.class, 64, "slugOld");
        NinjinEntities.createEntity(EntitySlugYoung.class, 64, "slugYoung");
        NinjinEntities.createEntity(EntitySlugGiant.class, 64, "slugGiant");
        NinjinEntities.createEntity(EntityMedamatcha.class, 64, "medamatcha");
        NinjinEntities.createEntity(EntityMedamatchaClone.class, 64, "medamatchaClone");
        NinjinEntities.createEntity(EntitySlugSoldier.class, 64, "slugSoldier");
        NinjinEntities.createEntity(EntityWings.class, 64, "wings");
        NinjinEntities.createEntity(EntityZeeun.class, 64, "zeeun");
        NinjinEntities.createEntity(EntityAndroid13.class, 64, "android13");
        NinjinEntities.createEntity(EntityAndroid13Super.class, 64, "android13Super");
        NinjinEntities.createEntity(EntityAndroid14.class, 64, "android14");
        NinjinEntities.createEntity(EntityAndroid15.class, 64, "android15");
        NinjinEntities.createEntity(EntityArbee.class, 64, "arbee");
        NinjinEntities.createEntity(EntityBudo.class, 64, "budo");
        NinjinEntities.createEntity(EntityGure.class, 64, "gure");
        NinjinEntities.createEntity(EntityJiku.class, 64, "jiku");
        NinjinEntities.createEntity(EntityKawazu.class, 64, "kawazu");
        NinjinEntities.createEntity(EntityKinkarn.class, 64, "kinkarn");
        NinjinEntities.createEntity(EntityPonkarn.class, 64, "ponkarn");
        NinjinEntities.createEntity(EntitySkud.class, 64, "skud");
        NinjinEntities.createEntity(EntityHatchiyack.class, 64, "hatchiyack");
        NinjinEntities.createEntity(EntityHatchiyackSuper.class, 64, "hatchiyackSuper");
        NinjinEntities.createEntity(EntityHatchiyackGiant.class, 64, "hatchiyackGiant");
        NinjinEntities.createEntity(EntityCyclopianGuard.class, 64, "cyclopianGuard");
        NinjinEntities.createEntity(EntityCoolerMetal.class, 64, "coolerMetal");
        NinjinEntities.createEntity(EntityCoolerMetalTrueForm.class, 64, "coolerMetalTrueForm");
        NinjinEntities.createEntity(EntityGoldCoolerMetal.class, 64, "GoldCoolerMetal");
        NinjinEntities.createEntity(EntityAmond.class, 64, "amond");
        NinjinEntities.createEntity(EntityCacao.class, 64, "cacao");
        NinjinEntities.createEntity(EntityDaiz.class, 64, "daiz");
        NinjinEntities.createEntity(EntityRasin.class, 64, "rasin");
        NinjinEntities.createEntity(EntityLakasei.class, 64, "lakasei");
        NinjinEntities.createEntity(EntityTurles1.class, 64, "turles1");
        NinjinEntities.createEntity(EntityTurles2.class, 64, "turles2");
        NinjinEntities.createEntity(EntityTurles3.class, 64, "turles3");
        NinjinEntities.createEntity(EntityBiomen.class, 64, "biomen");
        NinjinEntities.createEntity(EntityDrWheelo.class, 64, "drWheelo");
        NinjinEntities.createEntity(EntityEbifurya.class, 64, "ebifurya");
        NinjinEntities.createEntity(EntityKishime.class, 64, "kishime");
        NinjinEntities.createEntity(EntityMisokatsun.class, 64, "misokatsun");
        NinjinEntities.createEntity(EntityHoi.class, 64, "hoi");
        NinjinEntities.createEntity(EntityHirudegarnPre.class, 64, "hirudegarnPre");
        NinjinEntities.createEntity(EntityHirudegarnBottom.class, 64, "hirudegarnBottom");
        NinjinEntities.createEntity(EntityHirudegarnUpper.class, 64, "hirudegarnUpper");
        NinjinEntities.createEntity(EntityHirudegarnPost.class, 64, "hirudegarnPost");
        NinjinEntities.createEntity(EntityAbo.class, 64, "abo");
        NinjinEntities.createEntity(EntityKado.class, 64, "kado");
        NinjinEntities.createEntity(EntityAka.class, 64, "aka");
        NinjinEntities.createEntity(EntityCell4Ninjin.class, 64, "cell4");
        NinjinEntities.createEntity(EntityRecoomeDamaged.class, 64, "recoomeDamaged");
        NinjinEntities.createEntity(EntityGoldcellNinjin.class, 64, "hjcell");
        NinjinEntities.createEntity(EntityChilled.class, 64, "qed");
        NinjinEntities.createEntity(EntityBdkNinjin.class, 64, "bdk");
        NinjinEntities.createEntity(EntityBdkssjNinjin.class, 64, "bdkssj");
        NinjinEntities.createEntity(EntityBdkssj3Ninjin.class, 64, "bdkssj3");
        NinjinEntities.createEntity(EntityBdkSsj4.class, 64, "bdkssj4");
        NinjinEntities.createEntity(EntityBdkssjbNinjin.class, 64, "bdkssjb");
        NinjinEntities.createEntity(EntityBdkssjb3Ninjin.class, 64, "bdkssjb3");
        NinjinEntities.createEntity(EntityBlackFrieza.class, 64, "hsfls");
        NinjinEntities.createEntity(EntityBb.class, 64, "beibi");
        NinjinEntities.createEntity(EntityBb2.class, 64, "beibi2");
        NinjinEntities.createEntity(EntityBbssj.class, 64, "beibissj");
        NinjinEntities.createEntity(EntityBbssj2.class, 64, "beibissj2");
        NinjinEntities.createEntity(EntityJs.class, 64, "jiasi");
        NinjinEntities.createEntity(EntityZsfls.class, 64, "zsfls");
        NinjinEntities.createEntity(EntityZsCoolerFifthForm.class, 64, "zsgl");
        NinjinEntities.createEntity(EntityGoldCoolerFifthForm.class, 64, "hjgl");
        NinjinEntities.createEntity(EntityGoldCooler.class, 64, "GoldCooler");
        NinjinEntities.createEntity(EntityBzGokuSsj.class, 64, "Bzgokussj");
        NinjinEntities.createEntity(EntityFu.class, 64, "fu");
        NinjinEntities.createEntity(EntityVegetaZw.class, 64, "Vegetazw");
        NinjinEntities.createEntity(EntityVegetaSsj4.class, 64, "VegetaSsj4");
        NinjinEntities.createEntity(EntityDragon.class, 64, "GTDragon");
        NinjinEntities.createEntity(Entityomega.class, 64, "omega");
        NinjinEntities.createEntity(Entityomega2.class, 64, "omega2");
        NinjinEntities.createEntity(Entity3Stars.class, 64, "3Stars");
        NinjinEntities.createEntity(Entity4Stars.class, 64, "4Stars");
        NinjinEntities.createEntity(EntityMara.class, 64, "mara");
        NinjinEntities.createEntity(EntityMara_Young.class, 64, "mara2");
        NinjinEntities.createEntity(EntityMara_Fusion.class, 64, "mara3");
        NinjinEntities.createEntity(EntityCellmax.class, 64, "cellmax");
        NinjinEntities.createEntity(EntityCellperfectmax.class, 64, "cellperfectmax");
        NinjinEntities.createEntity(EntityGamma1.class, 64, "Gamma1");
        NinjinEntities.createEntity(EntityGamma2.class, 64, "Gamma2");
        NinjinEntities.createEntity(EntitySuper17.class, 64, "super17");
        NinjinEntities.createEntity(EntityPiccolo2.class, 64, "Piccolo2");
        NinjinEntities.createEntity(EntityPiccolo3.class, 64, "Piccolo3");
        NinjinEntities.createEntity(EntityPiccolo4.class, 64, "Piccolo4");
        NinjinEntities.createEntity(EntityPiccolo5.class, 64, "Piccolo5");
        NinjinEntities.createEntity(EntityEldKaioshin.class, 64, "eldKaioshin");
        NinjinEntities.createEntity(EntityKibito.class, 64, "Kibito");
        NinjinEntities.createEntity(EntityBlockGoku.class, 64, "BlockGoku");
        NinjinEntities.createEntity(EntityBlockGokuSsjR.class, 64, "BlockGokuSsjR");
        NinjinEntities.createEntity(EntityBlockGokuSsjR3.class, 64, "BlockGokuSsjR3");
        NinjinEntities.createEntity(EntityTamagami_1.class, 64, "Tamagami1");
        NinjinEntities.createEntity(EntityTamagami_2.class, 64, "Tamagami2");
        NinjinEntities.createEntity(EntityTamagami_3.class, 64, "Tamagami3");
        NinjinEntities.createEntity(EntityKaioshin.class, 64, "Kaioshin");
        NinjinEntities.createEntity(EntityKaioshinChild.class, 64, "KaioshinChild");
        NinjinEntities.createEntity(EntityBlockGohanUltimate.class, 64, "BlockGohan");
        NinjinEntities.createEntity(EntityDAIMAGokuSsj4.class, 64, "DAIMAGokuSsj4");
        NinjinEntities.createEntity(EntityDAIMAGoku.class, 64, "DAIMAGoku");
        NinjinEntities.createEntity(EntityDAIMAGokuSsj.class, 64, "DAIMAGokuSsj");
        NinjinEntities.createEntity(EntityDAIMAGokuSsj2.class, 64, "DAIMAGokuSsj2");
        NinjinEntities.createEntity(EntityDAIMAGokuSsj3.class, 64, "DAIMAGokuSsj3");
        NinjinEntities.createEntity(EntityDAIMAPorunga.class, 64, "DAIMAPorunga");
        NinjinEntities.createEntity(EntityDAIMAMajinKuu.class, 64, "MajinKuu");
        NinjinEntities.createEntity(EntityDAIMAMajinDuu.class, 64, "MajinDuu");
        NinjinEntities.createEntity(EntityDAIMAMajinDuuSsj3.class, 64, "MajinDuu2");
        NinjinEntities.createEntity(EntityPorungaNinjin.class, 64, "PorungaNinjin");
        NinjinEntities.createEntity(EntityDAIMAVegetaSsj3.class, 64, "DAIMAVegetaSsj3");
        NinjinEntities.createEntity(EntityGomahThirdEye.class, 64, "GomahThirdEye");
        NinjinEntities.createEntity(EntityGomahThirdEyeGigantic.class, 64, "GomahThirdEyeGigantic");
        NinjinEntities.createEntity(EntityXicor.class, 64, "Xicor");
        NinjinEntities.createEntity(EntityXicorSsj.class, 64, "XicorSsj");
        NinjinEntities.createEntity(EntityGoldOozaru.class, 64, "GoldOozaru");
        NinjinEntities.createEntity(EntityBbGoldOozaru.class, 64, "beibiGoldOozaru");
        NinjinEntities.createEntity(EntityPikkon.class, 64, "Pikkon");
        NinjinEntities.createEntity(Entity2Stars.class, 64, "2Stars");
        NinjinEntities.createEntity(Entity3Stars.class, 64, "3Stars");
        NinjinEntities.createEntity(Entity4Stars.class, 64, "4Stars");
        NinjinEntities.createEntity(Entity4StarsFullPower.class, 64, "4StarsFullPower");
        NinjinEntities.createEntity(Entity5Stars.class, 64, "5Stars");
        NinjinEntities.createEntity(Entity5StarsFullPower.class, 64, "5StarsFullPower");
        NinjinEntities.createEntity(Entity6Stars.class, 64, "6Stars");
        NinjinEntities.createEntity(Entity6StarsTrueform.class, 64, "6StarsTrueform");
        NinjinEntities.createEntity(Entity7Stars.class, 64, "7Stars");
        NinjinEntities.createEntity(Entity7StarsPan.class, 64, "7StarsPan");
        NinjinEntities.createEntity(Entity7StarsTrue.class, 64, "7StarsTrue");
        NinjinEntities.createEntity(Entitylude.class, 64, "lude");
        NinjinEntities.createEntity(EntityludeFullPower.class, 64, "ludeFullPower");
        NinjinEntities.createEntity(EntityLedgic.class, 64, "Ledgic");
        NinjinEntities.createEntity(Entitylierde.class, 64, "lierde");
        NinjinEntities.createEntity(Entityhetilierde.class, 64, "hetilierde");
    }

    public static void createEntity(Class entityClass, int trackingRange, String entityName) {
        EntityRegistry.registerModEntity((Class)entityClass, (String)entityName, (int)entityId, (Object)"ninjinentities", (int)trackingRange, (int)1, (boolean)true);
        ++entityId;
    }
}

