/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  cpw.mods.fml.common.registry.GameRegistry
 *  net.minecraft.item.Item
 */
package me.NBArmors.armors;

import cpw.mods.fml.common.registry.GameRegistry;
import me.NBArmors.armors.ArmorNB;
import me.NBArmors.items.ItemHeadNB;
import me.NBArmors.items.ItemVanityNB;
import me.NBArmors.tabs.NBTab;
import net.minecraft.item.Item;

public class dbs {
    public static Item bardockdbs_chest;
    public static Item bardockdbs_legs;
    public static Item bardockdbs_boots;
    public static Item brolys_chest;
    public static Item brolys_legs;
    public static Item brolys_boots;
    public static Item bulma12_chest;
    public static Item bulma12_legs;
    public static Item bulma12_boots;
    public static Item bulma4_chest;
    public static Item bulma4_legs;
    public static Item bulma4_boots;
    public static Item cellmax_head;
    public static Item cellmax_chest;
    public static Item cellmax_legs;
    public static Item cellmax_boots;
    public static Item c18dbsh_chest;
    public static Item c18dbsh_legs;
    public static Item c18dbsh_boots;
    public static Item dercori_chest;
    public static Item farmgoku_chest;
    public static Item farmgoku_legs;
    public static Item farmgoku_boots;
    public static Item gamma1_chest;
    public static Item gamma2_chest;
    public static Item gamma1_legs;
    public static Item gamma1_boots;
    public static Item gammaf1_chest;
    public static Item gammaf1_legs;
    public static Item gammaf1_boots;
    public static Item gammaf2_chest;
    public static Item gammaf2_legs;
    public static Item gammaf2_boots;
    public static Item gasb;
    public static Item gas_chest;
    public static Item gas_legs;
    public static Item gas_boots;
    public static Item gbb0_chest;
    public static Item gbb1_chest;
    public static Item gbb2_chest;
    public static Item gbb3_chest;
    public static Item gbb4_chest;
    public static Item gbb0_legs;
    public static Item gbb4_legs;
    public static Item gbb0_boots;
    public static Item gine_chest;
    public static Item gine_legs;
    public static Item gine_boots;
    public static Item gohansh_chest;
    public static Item gohansh_legs;
    public static Item gohansh_boots;
    public static Item gotendbsh_chest;
    public static Item gotendbsh_legs;
    public static Item gotendbsh_boots;
    public static Item granola_chest;
    public static Item granola_legs;
    public static Item granola_boots;
    public static Item hit1_chest;
    public static Item hit1_legs;
    public static Item hit1_boots;
    public static Item hop_chest;
    public static Item hop_legs;
    public static Item hop_boots;
    public static Item jaco_chest;
    public static Item jaco_legs;
    public static Item jaco_boots;
    public static Item kakunsamask;
    public static Item kakunsa_chest;
    public static Item kakunsa_legs;
    public static Item kakunsa_boots;
    public static Item katopesla_head;
    public static Item katopesla_chest;
    public static Item katopesla_legs;
    public static Item katopesla_boots;
    public static Item katopeslab_head;
    public static Item katopeslab_chest;
    public static Item katopeslab_legs;
    public static Item katopeslab_boots;
    public static Item katopeslas_head;
    public static Item katopeslas_chest;
    public static Item katopeslas_legs;
    public static Item katopeslas_boots;
    public static Item katopeslau_head;
    public static Item katopeslau_chest;
    public static Item katopeslau_legs;
    public static Item katopeslau_boots;
    public static Item kefla_chest;
    public static Item kefla_legs;
    public static Item kefla_boots;
    public static Item kvegetas_chest;
    public static Item kvegetas_legs;
    public static Item kvegetas_boots;
    public static Item maki_chest;
    public static Item maki_legs;
    public static Item maki_boots;
    public static Item meru_head;
    public static Item meru_chest;
    public static Item meru_legs;
    public static Item meru_boots;
    public static Item monakac_head;
    public static Item monakac_chest;
    public static Item monakac_legs;
    public static Item monakac_boots;
    public static Item piccolosh_chest;
    public static Item piccolosh_legs;
    public static Item piccolosh_boots;
    public static Item rrsoldier1_head;
    public static Item rrsoldier2_head;
    public static Item rrsoldier1_chest;
    public static Item rrsoldier2_chest;
    public static Item rrsoldier1_legs;
    public static Item rrsoldier1_boots;
    public static Item saiyamanx1_head;
    public static Item saiyamanx1_chest;
    public static Item saiyamanx1_legs;
    public static Item saiyamanx1_boots;
    public static Item saiyamanx2_head;
    public static Item saiyamanx2_chest;
    public static Item saiyamanx2_legs;
    public static Item saiyamanx2_boots;
    public static Item tagoma_chest;
    public static Item tagoma_legs;
    public static Item tagoma_boots;
    public static Item trunksdbs_chest;
    public static Item trunksdbs_legs;
    public static Item trunksdbs_boots;
    public static Item trunksdbsh_chest;
    public static Item trunksdbsh_legs;
    public static Item trunksdbsh_boots;

    public static void mainRegistry() {
        dbs.initiliseItem();
        dbs.registerItem();
    }

    public static void initiliseItem() {
    }

    public static void registerItem() {
        bardockdbs_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "bardockdbs").func_77655_b("bardockdbs_chest").func_77637_a(NBTab.dbs), (String)"bardockdbs_chest", null);
        bardockdbs_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "bardockdbs").func_77655_b("bardockdbs_legs").func_77637_a(NBTab.dbs), (String)"bardockdbs_legs", null);
        bardockdbs_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "bardockdbs").func_77655_b("bardockdbs_boots").func_77637_a(NBTab.dbs), (String)"bardockdbs_boots", null);
        brolys_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "brolys").func_77655_b("brolys_chest").func_77637_a(NBTab.dbs), (String)"brolys_chest", null);
        brolys_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "brolys").func_77655_b("brolys_legs").func_77637_a(NBTab.dbs), (String)"brolys_legs", null);
        brolys_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "brolys").func_77655_b("brolys_boots").func_77637_a(NBTab.dbs), (String)"brolys_boots", null);
        bulma12_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "bulma12").func_77655_b("bulma12_chest").func_77637_a(NBTab.dbs), (String)"bulma12_chest", null);
        bulma12_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "bulma12").func_77655_b("bulma12_legs").func_77637_a(NBTab.dbs), (String)"bulma12_legs", null);
        bulma12_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "bulma12").func_77655_b("bulma12_boots").func_77637_a(NBTab.dbs), (String)"bulma12_boots", null);
        bulma4_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "bulma4").func_77655_b("bulma4_chest").func_77637_a(NBTab.dbs), (String)"bulma4_chest", null);
        bulma4_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "bulma4").func_77655_b("bulma4_legs").func_77637_a(NBTab.dbs), (String)"bulma4_legs", null);
        bulma4_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "bulma4").func_77655_b("bulma4_boots").func_77637_a(NBTab.dbs), (String)"bulma4_boots", null);
        cellmax_head = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 0, "cellmax").func_77655_b("cellmax_head").func_77637_a(NBTab.dbs), (String)"cellmax_head", null);
        cellmax_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "cellmax").func_77655_b("cellmax_chest").func_77637_a(NBTab.dbs), (String)"cellmax_chest", null);
        cellmax_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "cellmax").func_77655_b("cellmax_legs").func_77637_a(NBTab.dbs), (String)"cellmax_legs", null);
        cellmax_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "cellmax").func_77655_b("cellmax_boots").func_77637_a(NBTab.dbs), (String)"cellmax_boots", null);
        c18dbsh_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "c18dbsh").func_77655_b("c18dbsh_chest").func_77637_a(NBTab.dbs), (String)"c18dbsh_chest", null);
        c18dbsh_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "c18dbsh").func_77655_b("c18dbsh_legs").func_77637_a(NBTab.dbs), (String)"c18dbsh_legs", null);
        c18dbsh_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "c18dbsh").func_77655_b("c18dbsh_boots").func_77637_a(NBTab.dbs), (String)"c18dbsh_boots", null);
        dercori_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "dercori").func_77655_b("dercori_chest").func_77637_a(NBTab.dbs), (String)"dercori_chest", null);
        farmgoku_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "farmgoku").func_77655_b("farmgoku_chest").func_77637_a(NBTab.dbs), (String)"farmgoku_chest", null);
        farmgoku_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "farmgoku").func_77655_b("farmgoku_legs").func_77637_a(NBTab.dbs), (String)"farmgoku_legs", null);
        farmgoku_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "farmgoku").func_77655_b("farmgoku_boots").func_77637_a(NBTab.dbs), (String)"farmgoku_boots", null);
        gamma1_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "gamma1").func_77655_b("gamma1_chest").func_77637_a(NBTab.dbs), (String)"gamma1_chest", null);
        gamma2_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "gamma2").func_77655_b("gamma2_chest").func_77637_a(NBTab.dbs), (String)"gamma2_chest", null);
        gamma1_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "gamma1").func_77655_b("gamma1_legs").func_77637_a(NBTab.dbs), (String)"gamma1_legs", null);
        gamma1_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "gamma1").func_77655_b("gamma1_boots").func_77637_a(NBTab.dbs), (String)"gamma1_boots", null);
        gammaf1_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "gammaf1").func_77655_b("gammaf1_chest").func_77637_a(NBTab.dbs), (String)"gammaf1_chest", null);
        gammaf1_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "gammaf1").func_77655_b("gammaf1_legs").func_77637_a(NBTab.dbs), (String)"gammaf1_legs", null);
        gammaf1_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "gammaf1").func_77655_b("gammaf1_boots").func_77637_a(NBTab.dbs), (String)"gammaf1_boots", null);
        gammaf2_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "gammaf2").func_77655_b("gammaf2_chest").func_77637_a(NBTab.dbs), (String)"gammaf2_chest", null);
        gammaf2_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "gammaf2").func_77655_b("gammaf2_legs").func_77637_a(NBTab.dbs), (String)"gammaf2_legs", null);
        gammaf2_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "gammaf2").func_77655_b("gammaf2_boots").func_77637_a(NBTab.dbs), (String)"gammaf2_boots", null);
        gasb = GameRegistry.registerItem((Item)new ItemVanityNB(0xFFFFFF, ArmorNB.NBmaterial, 0, "gasb", 4).func_77655_b("gasb").func_77637_a(NBTab.dbs), (String)"gasb", null);
        gas_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "gas").func_77655_b("gas_chest").func_77637_a(NBTab.dbs), (String)"gas_chest", null);
        gas_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "gas").func_77655_b("gas_legs").func_77637_a(NBTab.dbs), (String)"gas_legs", null);
        gas_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "gas").func_77655_b("gas_boots").func_77637_a(NBTab.dbs), (String)"gas_boots", null);
        gbb0_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "gbb0").func_77655_b("gbb0_chest").func_77637_a(NBTab.dbs), (String)"gbb0_chest", null);
        gbb1_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "gbb1").func_77655_b("gbb1_chest").func_77637_a(NBTab.dbs), (String)"gbb1_chest", null);
        gbb2_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "gbb2").func_77655_b("gbb2_chest").func_77637_a(NBTab.dbs), (String)"gbb2_chest", null);
        gbb3_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "gbb3").func_77655_b("gbb3_chest").func_77637_a(NBTab.dbs), (String)"gbb3_chest", null);
        gbb4_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "gbb4").func_77655_b("gbb4_chest").func_77637_a(NBTab.dbs), (String)"gbb4_chest", null);
        gbb0_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "gbb0").func_77655_b("gbb0_legs").func_77637_a(NBTab.dbs), (String)"gbb0_legs", null);
        gbb4_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "gbb4").func_77655_b("gbb4_legs").func_77637_a(NBTab.dbs), (String)"gbb4_legs", null);
        gbb0_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "gbb0").func_77655_b("gbb0_boots").func_77637_a(NBTab.dbs), (String)"gbb0_boots", null);
        gine_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "gine").func_77655_b("gine_chest").func_77637_a(NBTab.dbs), (String)"gine_chest", null);
        gine_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "gine").func_77655_b("gine_legs").func_77637_a(NBTab.dbs), (String)"gine_legs", null);
        gine_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "gine").func_77655_b("gine_boots").func_77637_a(NBTab.dbs), (String)"gine_boots", null);
        gohansh_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "gohansh").func_77655_b("gohansh_chest").func_77637_a(NBTab.dbs), (String)"gohansh_chest", null);
        gohansh_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "gohansh").func_77655_b("gohansh_legs").func_77637_a(NBTab.dbs), (String)"gohansh_legs", null);
        gohansh_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "gohansh").func_77655_b("gohansh_boots").func_77637_a(NBTab.dbs), (String)"gohansh_boots", null);
        gotendbsh_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "gotendbsh").func_77655_b("gotendbsh_chest").func_77637_a(NBTab.dbs), (String)"gotendbsh_chest", null);
        gotendbsh_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "gotendbsh").func_77655_b("gotendbsh_legs").func_77637_a(NBTab.dbs), (String)"gotendbsh_legs", null);
        gotendbsh_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "gotendbsh").func_77655_b("gotendbsh_boots").func_77637_a(NBTab.dbs), (String)"gotendbsh_boots", null);
        granola_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "granola").func_77655_b("granola_chest").func_77637_a(NBTab.dbs), (String)"granola_chest", null);
        granola_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "granola").func_77655_b("granola_legs").func_77637_a(NBTab.dbs), (String)"granola_legs", null);
        granola_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "granola").func_77655_b("granola_boots").func_77637_a(NBTab.dbs), (String)"granola_boots", null);
        hit1_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "hit1").func_77655_b("hit1_chest").func_77637_a(NBTab.dbs), (String)"hit1_chest", null);
        hit1_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "hit1").func_77655_b("hit1_legs").func_77637_a(NBTab.dbs), (String)"hit1_legs", null);
        hit1_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "hit1").func_77655_b("hit1_boots").func_77637_a(NBTab.dbs), (String)"hit1_boots", null);
        hop_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "hop").func_77655_b("hop_chest").func_77637_a(NBTab.dbs), (String)"hop_chest", null);
        hop_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "hop").func_77655_b("hop_legs").func_77637_a(NBTab.dbs), (String)"hop_legs", null);
        hop_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "hop").func_77655_b("hop_boots").func_77637_a(NBTab.dbs), (String)"hop_boots", null);
        jaco_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "jaco").func_77655_b("jaco_chest").func_77637_a(NBTab.dbs), (String)"jaco_chest", null);
        jaco_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "jaco").func_77655_b("jaco_legs").func_77637_a(NBTab.dbs), (String)"jaco_legs", null);
        jaco_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "jaco").func_77655_b("jaco_boots").func_77637_a(NBTab.dbs), (String)"jaco_boots", null);
        kakunsamask = GameRegistry.registerItem((Item)new ItemVanityNB(0xFFFFFF, ArmorNB.NBmaterial, 0, "kakunsamask", 3).func_77655_b("kakunsamask").func_77637_a(NBTab.dbs), (String)"kakunsamask", null);
        kakunsa_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "kakunsa").func_77655_b("kakunsa_chest").func_77637_a(NBTab.dbs), (String)"kakunsa_chest", null);
        kakunsa_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "kakunsa").func_77655_b("kakunsa_legs").func_77637_a(NBTab.dbs), (String)"kakunsa_legs", null);
        kakunsa_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "kakunsa").func_77655_b("kakunsa_boots").func_77637_a(NBTab.dbs), (String)"kakunsa_boots", null);
        katopesla_head = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 0, "katopesla").func_77655_b("katopesla_head").func_77637_a(NBTab.dbs), (String)"katopesla_head", null);
        katopesla_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "katopesla").func_77655_b("katopesla_chest").func_77637_a(NBTab.dbs), (String)"katopesla_chest", null);
        katopesla_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "katopesla").func_77655_b("katopesla_legs").func_77637_a(NBTab.dbs), (String)"katopesla_legs", null);
        katopesla_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "katopesla").func_77655_b("katopesla_boots").func_77637_a(NBTab.dbs), (String)"katopesla_boots", null);
        katopeslab_head = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 0, "katopeslab").func_77655_b("katopeslab_head").func_77637_a(NBTab.dbs), (String)"katopeslab_head", null);
        katopeslab_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "katopeslab").func_77655_b("katopeslab_chest").func_77637_a(NBTab.dbs), (String)"katopeslab_chest", null);
        katopeslab_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "katopeslab").func_77655_b("katopeslab_legs").func_77637_a(NBTab.dbs), (String)"katopeslab_legs", null);
        katopeslab_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "katopeslab").func_77655_b("katopeslab_boots").func_77637_a(NBTab.dbs), (String)"katopeslab_boots", null);
        katopeslas_head = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 0, "katopeslas").func_77655_b("katopeslas_head").func_77637_a(NBTab.dbs), (String)"katopeslas_head", null);
        katopeslas_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "katopeslas").func_77655_b("katopeslas_chest").func_77637_a(NBTab.dbs), (String)"katopeslas_chest", null);
        katopeslas_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "katopeslas").func_77655_b("katopeslas_legs").func_77637_a(NBTab.dbs), (String)"katopeslas_legs", null);
        katopeslas_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "katopeslas").func_77655_b("katopeslas_boots").func_77637_a(NBTab.dbs), (String)"katopeslas_boots", null);
        katopeslau_head = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 0, "katopeslau").func_77655_b("katopeslau_head").func_77637_a(NBTab.dbs), (String)"katopeslau_head", null);
        katopeslau_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "katopeslau").func_77655_b("katopeslau_chest").func_77637_a(NBTab.dbs), (String)"katopeslau_chest", null);
        katopeslau_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "katopeslau").func_77655_b("katopeslau_legs").func_77637_a(NBTab.dbs), (String)"katopeslau_legs", null);
        katopeslau_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "katopeslau").func_77655_b("katopeslau_boots").func_77637_a(NBTab.dbs), (String)"katopeslau_boots", null);
        kefla_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "kefla").func_77655_b("kefla_chest").func_77637_a(NBTab.dbs), (String)"kefla_chest", null);
        kefla_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "kefla").func_77655_b("kefla_legs").func_77637_a(NBTab.dbs), (String)"kefla_legs", null);
        kefla_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "kefla").func_77655_b("kefla_boots").func_77637_a(NBTab.dbs), (String)"kefla_boots", null);
        kvegetas_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "kvegetas").func_77655_b("kvegetas_chest").func_77637_a(NBTab.dbs), (String)"kvegetas_chest", null);
        kvegetas_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "kvegetas").func_77655_b("kvegetas_legs").func_77637_a(NBTab.dbs), (String)"kvegetas_legs", null);
        kvegetas_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "kvegetas").func_77655_b("kvegetas_boots").func_77637_a(NBTab.dbs), (String)"kvegetas_boots", null);
        maki_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "maki").func_77655_b("maki_chest").func_77637_a(NBTab.dbs), (String)"maki_chest", null);
        maki_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "maki").func_77655_b("maki_legs").func_77637_a(NBTab.dbs), (String)"maki_legs", null);
        maki_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "maki").func_77655_b("maki_boots").func_77637_a(NBTab.dbs), (String)"maki_boots", null);
        meru_head = GameRegistry.registerItem((Item)new ItemHeadNB("meru", "3").func_77655_b("meru_head").func_77637_a(NBTab.dbs), (String)"meru_head", null);
        meru_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "meru").func_77655_b("meru_chest").func_77637_a(NBTab.dbs), (String)"meru_chest", null);
        meru_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "meru").func_77655_b("meru_legs").func_77637_a(NBTab.dbs), (String)"meru_legs", null);
        meru_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "meru").func_77655_b("meru_boots").func_77637_a(NBTab.dbs), (String)"meru_boots", null);
        monakac_head = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 0, "monakac").func_77655_b("monakac_head").func_77637_a(NBTab.dbs), (String)"monakac_head", null);
        monakac_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "monakac").func_77655_b("monakac_chest").func_77637_a(NBTab.dbs), (String)"monakac_chest", null);
        monakac_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "monakac").func_77655_b("monakac_legs").func_77637_a(NBTab.dbs), (String)"monakac_legs", null);
        monakac_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "monakac").func_77655_b("monakac_boots").func_77637_a(NBTab.dbs), (String)"monakac_boots", null);
        piccolosh_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "piccolosh").func_77655_b("piccolosh_chest").func_77637_a(NBTab.dbs), (String)"piccolosh_chest", null);
        piccolosh_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "piccolosh").func_77655_b("piccolosh_legs").func_77637_a(NBTab.dbs), (String)"piccolosh_legs", null);
        piccolosh_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "piccolosh").func_77655_b("piccolosh_boots").func_77637_a(NBTab.dbs), (String)"piccolosh_boots", null);
        rrsoldier1_head = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 0, "rrsoldier1").func_77655_b("rrsoldier1_head").func_77637_a(NBTab.dbs), (String)"rrsoldier1_head", null);
        rrsoldier1_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "rrsoldier1").func_77655_b("rrsoldier1_chest").func_77637_a(NBTab.dbs), (String)"rrsoldier1_chest", null);
        rrsoldier2_head = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 0, "rrsoldier2").func_77655_b("rrsoldier2_head").func_77637_a(NBTab.dbs), (String)"rrsoldier2_head", null);
        rrsoldier2_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "rrsoldier2").func_77655_b("rrsoldier2_chest").func_77637_a(NBTab.dbs), (String)"rrsoldier2_chest", null);
        rrsoldier1_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "rrsoldier1").func_77655_b("rrsoldier1_legs").func_77637_a(NBTab.dbs), (String)"rrsoldier1_legs", null);
        rrsoldier1_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "rrsoldier1").func_77655_b("rrsoldier1_boots").func_77637_a(NBTab.dbs), (String)"rrsoldier1_boots", null);
        saiyamanx1_head = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 0, "saiyamanx1").func_77655_b("saiyamanx1_head").func_77637_a(NBTab.dbs), (String)"saiyamanx1_head", null);
        saiyamanx1_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "saiyamanx1").func_77655_b("saiyamanx1_chest").func_77637_a(NBTab.dbs), (String)"saiyamanx1_chest", null);
        saiyamanx1_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "saiyamanx1").func_77655_b("saiyamanx1_legs").func_77637_a(NBTab.dbs), (String)"saiyamanx1_legs", null);
        saiyamanx1_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "saiyamanx1").func_77655_b("saiyamanx1_boots").func_77637_a(NBTab.dbs), (String)"saiyamanx1_boots", null);
        saiyamanx2_head = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 0, "saiyamanx2").func_77655_b("saiyamanx2_head").func_77637_a(NBTab.dbs), (String)"saiyamanx2_head", null);
        saiyamanx2_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "saiyamanx2").func_77655_b("saiyamanx2_chest").func_77637_a(NBTab.dbs), (String)"saiyamanx2_chest", null);
        saiyamanx2_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "saiyamanx2").func_77655_b("saiyamanx2_legs").func_77637_a(NBTab.dbs), (String)"saiyamanx2_legs", null);
        saiyamanx2_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "saiyamanx2").func_77655_b("saiyamanx2_boots").func_77637_a(NBTab.dbs), (String)"saiyamanx2_boots", null);
        tagoma_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "tagoma").func_77655_b("tagoma_chest").func_77637_a(NBTab.dbs), (String)"tagoma_chest", null);
        tagoma_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "tagoma").func_77655_b("tagoma_legs").func_77637_a(NBTab.dbs), (String)"tagoma_legs", null);
        tagoma_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "tagoma").func_77655_b("tagoma_boots").func_77637_a(NBTab.dbs), (String)"tagoma_boots", null);
        trunksdbs_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "trunksdbs").func_77655_b("trunksdbs_chest").func_77637_a(NBTab.dbs), (String)"trunksdbs_chest", null);
        trunksdbs_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "trunksdbs").func_77655_b("trunksdbs_legs").func_77637_a(NBTab.dbs), (String)"trunksdbs_legs", null);
        trunksdbs_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "trunksdbs").func_77655_b("trunksdbs_boots").func_77637_a(NBTab.dbs), (String)"trunksdbs_boots", null);
        trunksdbsh_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "trunksdbsh").func_77655_b("trunksdbsh_chest").func_77637_a(NBTab.dbs), (String)"trunksdbsh_chest", null);
        trunksdbsh_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "trunksdbsh").func_77655_b("trunksdbsh_legs").func_77637_a(NBTab.dbs), (String)"trunksdbsh_legs", null);
        trunksdbsh_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "trunksdbsh").func_77655_b("trunksdbsh_boots").func_77637_a(NBTab.dbs), (String)"trunksdbsh_boots", null);
    }
}

