/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  cpw.mods.fml.common.registry.GameRegistry
 *  net.minecraft.item.Item
 */
package me.NBArmors.armors;

import cpw.mods.fml.common.registry.GameRegistry;
import me.NBArmors.armors.ArmorNB;
import me.NBArmors.armors.ArmorNB2;
import me.NBArmors.armors.MarksNB;
import me.NBArmors.items.ItemHeadNB;
import me.NBArmors.tabs.NBTab;
import net.minecraft.item.Item;

public class dbz {
    public static Item almond_chest;
    public static Item almond_legs;
    public static Item almond_boots;
    public static Item bardockz_chest;
    public static Item bardockz_legs;
    public static Item bardockz_boots;
    public static Item bido_chest;
    public static Item bido_legs;
    public static Item bojack_chest;
    public static Item bojack_legs;
    public static Item brolym_chest;
    public static Item brolym_legs;
    public static Item brolym_boots;
    public static Item bujin_head;
    public static Item bujin_chest;
    public static Item bujin_legs;
    public static Item bulma1_chest;
    public static Item bulma1_legs;
    public static Item bulma1_boots;
    public static Item bulma11_head;
    public static Item bulma11_chest;
    public static Item bulma11_legs;
    public static Item bulma11_boots;
    public static Item bulma2_chest;
    public static Item bulma2_legs;
    public static Item bulma2_boots;
    public static Item bvegeta_chest;
    public static Item bvegeta_legs;
    public static Item bvegeta_boots;
    public static Item c13_head;
    public static Item c13_chest;
    public static Item c13_legs;
    public static Item c13_boots;
    public static Item c14_chest;
    public static Item c14_legs;
    public static Item c14_boots;
    public static Item c15_head;
    public static Item c15_chest;
    public static Item c15_legs;
    public static Item c15_boots;
    public static Item celula_head;
    public static Item celula_chest;
    public static Item celula_legs;
    public static Item celula_boots;
    public static Item daiz_chest;
    public static Item daiz_boots;
    public static Item dengoku_chest;
    public static Item dgoku_chest;
    public static Item dgoku_legs;
    public static Item dgoku_boots;
    public static Item dgokuss_chest;
    public static Item dgokuss_legs;
    public static Item dvegetabuu_chest;
    public static Item dvegetabuu_legs;
    public static Item dvegetabuu_boots;
    public static Item dvegetaf_chest;
    public static Item dvegetaf_legs;
    public static Item dvegetaf_boots;
    public static Item dvegetas_chest;
    public static Item dvegetas_legs;
    public static Item dvegetas_boots;
    public static Item freeza_head;
    public static Item freeza_chest;
    public static Item freeza_legs;
    public static Item freeza_boots;
    public static Item freeza1_chest;
    public static Item ginyuf0_chest;
    public static Item ginyuf0_legs;
    public static Item ginyuf0_boots;
    public static Item ginyuf1_chest;
    public static Item ginyuf1_boots;
    public static Item gohankai_chest;
    public static Item gohankai_legs;
    public static Item gohankai_boots;
    public static Item gohanwest_head;
    public static Item gohanwest_chest;
    public static Item gohanwest_legs;
    public static Item gohanwest_boots;
    public static Item gokueoz_chest;
    public static Item gokueoz_legs;
    public static Item gokueoz_boots;
    public static Item gokugo_chest;
    public static Item gokugo_legs;
    public static Item gokugo_boots;
    public static Item gokujacket_chest;
    public static Item gokujacket_legs;
    public static Item gokujacket_boots;
    public static Item gokuss_chest;
    public static Item gokuss_legs;
    public static Item gokuss_boots;
    public static Item gokuteen_chest;
    public static Item gokuteen_legs;
    public static Item gokuteen_boots;
    public static Item gokuy_chest;
    public static Item gsoldier_boots;
    public static Item janemba_head;
    public static Item janemba1_head;
    public static Item janemba_chest;
    public static Item janemba1_chest;
    public static Item janemba_legs;
    public static Item janemba_boots;
    public static Item kcold_chest;
    public static Item kogu_chest;
    public static Item kogu_legs;
    public static Item kvegetaz_chest;
    public static Item kvegetaz_legs;
    public static Item kvegetaz_boots;
    public static Item mfrieza_head;
    public static Item mfrieza_chest;
    public static Item mfrieza_legs;
    public static Item mfrieza_boots;
    public static Item mightymask_head;
    public static Item mightymask_chest;
    public static Item mightymask_legs;
    public static Item mightymask_boots;
    public static Item nail_chest;
    public static Item nail_legs;
    public static Item nail_boots;
    public static Item olivue_chest;
    public static Item olivue_legs;
    public static Item olivue_boots;
    public static Item pikkon_head;
    public static Item pikkon_chest;
    public static Item pikkon_legs;
    public static Item pikkon_boots;
    public static Item postboy_chest;
    public static Item postboy_legs;
    public static Item postboy_boots;
    public static Item raditz_chest;
    public static Item raditz_boots;
    public static Item ryl_chest;
    public static Item ryl_legs;
    public static Item ryl_boots;
    public static Item saiyagirl_head;
    public static Item saiyagirl_chest;
    public static Item saiyagirl_legs;
    public static Item saiyagirl_boots;
    public static Item saiyan_chest;
    public static Item saiyan_legs;
    public static Item saiyan_boots;
    public static Item salza_chest;
    public static Item salza_legs;
    public static Item salza_boots;
    public static Item selypar_chest;
    public static Item selypar_legs;
    public static Item selypar_boots;
    public static Item tapion_head;
    public static Item tapion_chest;
    public static Item tapion_legs;
    public static Item tapion_boots;
    public static Item trunksdbz_chest;
    public static Item trunksdbz_legs;
    public static Item trunksdbz_boots;
    public static Item trunksdbzf_chest;
    public static Item trunksdbzf_legs;
    public static Item trunksdbzf_boots;
    public static Item trunksfjacket;
    public static Item trunksfwaistcoat;
    public static Item trunksf_chest;
    public static Item trunksf_legs;
    public static Item trunksf_boots;
    public static Item trunkspre_chest;
    public static Item trunkspre_legs;
    public static Item trunkspre_boots;
    public static Item tsufuru_chest;
    public static Item tsufuru_legs;
    public static Item tsufuru_boots;
    public static Item turles_chest;
    public static Item turles_boots;
    public static Item vegetabuu_chest;
    public static Item vegetabuu_legs;
    public static Item vegetabuu_boots;
    public static Item vegetacs_chest;
    public static Item vegetacs_legs;
    public static Item vegetacs_boots;
    public static Item vegetaeoz_chest;
    public static Item vegetaeoz_legs;
    public static Item vegetaeoz_boots;
    public static Item vegetafr_chest;
    public static Item vegetafr_legs;
    public static Item vegetafr_boots;
    public static Item vegetasc_chest;
    public static Item vegetasc_legs;
    public static Item vegetasc_boots;
    public static Item vegetasca_chest;
    public static Item vegetasca_legs;
    public static Item vegetasca_boots;
    public static Item zangya_chest;
    public static Item zangya_legs;

    public static void mainRegistry() {
        dbz.initiliseItem();
        dbz.registerItem();
    }

    public static void initiliseItem() {
    }

    public static void registerItem() {
        almond_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "almond").func_77655_b("almond_chest").func_77637_a(NBTab.dbz), (String)"almond_chest", null);
        almond_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "almond").func_77655_b("almond_legs").func_77637_a(NBTab.dbz), (String)"almond_legs", null);
        almond_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "almond").func_77655_b("almond_boots").func_77637_a(NBTab.dbz), (String)"almond_boots", null);
        bardockz_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "bardockz").func_77655_b("bardockz_chest").func_77637_a(NBTab.dbz), (String)"bardockz_chest", null);
        bardockz_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "bardockz").func_77655_b("bardockz_legs").func_77637_a(NBTab.dbz), (String)"bardockz_legs", null);
        bardockz_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "bardockz").func_77655_b("bardockz_boots").func_77637_a(NBTab.dbz), (String)"bardockz_boots", null);
        bido_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "bido").func_77655_b("bido_chest").func_77637_a(NBTab.dbz), (String)"bido_chest", null);
        bido_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "bido").func_77655_b("bido_legs").func_77637_a(NBTab.dbz), (String)"bido_legs", null);
        bojack_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "bojack").func_77655_b("bojack_chest").func_77637_a(NBTab.dbz), (String)"bojack_chest", null);
        bojack_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "bojack").func_77655_b("bojack_legs").func_77637_a(NBTab.dbz), (String)"bojack_legs", null);
        brolym_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "brolym").func_77655_b("brolym_chest").func_77637_a(NBTab.dbz), (String)"brolym_chest", null);
        brolym_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "brolym").func_77655_b("brolym_legs").func_77637_a(NBTab.dbz), (String)"brolym_legs", null);
        brolym_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "brolym").func_77655_b("brolym_boots").func_77637_a(NBTab.dbz), (String)"brolym_boots", null);
        bujin_head = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 0, "bujin").func_77655_b("bujin_head").func_77637_a(NBTab.dbz), (String)"bujin_head", null);
        bujin_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "bujin").func_77655_b("bujin_chest").func_77637_a(NBTab.dbz), (String)"bujin_chest", null);
        bujin_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "bujin").func_77655_b("bujin_legs").func_77637_a(NBTab.dbz), (String)"bujin_legs", null);
        bulma1_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "bulma1").func_77655_b("bulma1_chest").func_77637_a(NBTab.dbz), (String)"bulma1_chest", null);
        bulma1_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "bulma1").func_77655_b("bulma1_legs").func_77637_a(NBTab.dbz), (String)"bulma1_legs", null);
        bulma1_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "bulma1").func_77655_b("bulma1_boots").func_77637_a(NBTab.dbz), (String)"bulma1_boots", null);
        bulma11_head = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 0, "bulma11").func_77655_b("bulma11_head").func_77637_a(NBTab.dbz), (String)"bulma11_head", null);
        bulma11_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "bulma11").func_77655_b("bulma11_chest").func_77637_a(NBTab.dbz), (String)"bulma11_chest", null);
        bulma11_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "bulma11").func_77655_b("bulma11_legs").func_77637_a(NBTab.dbz), (String)"bulma11_legs", null);
        bulma11_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "bulma11").func_77655_b("bulma11_boots").func_77637_a(NBTab.dbz), (String)"bulma11_boots", null);
        bulma2_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "bulma2").func_77655_b("bulma2_chest").func_77637_a(NBTab.dbz), (String)"bulma2_chest", null);
        bulma2_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "bulma2").func_77655_b("bulma2_legs").func_77637_a(NBTab.dbz), (String)"bulma2_legs", null);
        bulma2_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "bulma2").func_77655_b("bulma2_boots").func_77637_a(NBTab.dbz), (String)"bulma2_boots", null);
        bvegeta_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "bvegeta").func_77655_b("bvegeta_chest").func_77637_a(NBTab.dbz), (String)"bvegeta_chest", null);
        bvegeta_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "bvegeta").func_77655_b("bvegeta_legs").func_77637_a(NBTab.dbz), (String)"bvegeta_legs", null);
        bvegeta_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "bvegeta").func_77655_b("bvegeta_boots").func_77637_a(NBTab.dbz), (String)"bvegeta_boots", null);
        c13_head = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 0, "c13").func_77655_b("c13_head").func_77637_a(NBTab.dbz), (String)"c13_head", null);
        c13_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "c13").func_77655_b("c13_chest").func_77637_a(NBTab.dbz), (String)"c13_chest", null);
        c13_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "c13").func_77655_b("c13_legs").func_77637_a(NBTab.dbz), (String)"c13_legs", null);
        c13_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "c13").func_77655_b("c13_boots").func_77637_a(NBTab.dbz), (String)"c13_boots", null);
        c14_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "c14").func_77655_b("c14_chest").func_77637_a(NBTab.dbz), (String)"c14_chest", null);
        c14_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "c14").func_77655_b("c14_legs").func_77637_a(NBTab.dbz), (String)"c14_legs", null);
        c14_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "c14").func_77655_b("c14_boots").func_77637_a(NBTab.dbz), (String)"c14_boots", null);
        c15_head = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 0, "c15").func_77655_b("c15_head").func_77637_a(NBTab.dbz), (String)"c15_head", null);
        c15_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "c15").func_77655_b("c15_chest").func_77637_a(NBTab.dbz), (String)"c15_chest", null);
        c15_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "c15").func_77655_b("c15_legs").func_77637_a(NBTab.dbz), (String)"c15_legs", null);
        c15_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "c15").func_77655_b("c15_boots").func_77637_a(NBTab.dbz), (String)"c15_boots", null);
        celula_head = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 0, "celula").func_77655_b("celula_head").func_77637_a(NBTab.dbz), (String)"celula_head", null);
        celula_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "celula").func_77655_b("celula_chest").func_77637_a(NBTab.dbz), (String)"celula_chest", null);
        celula_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "celula").func_77655_b("celula_legs").func_77637_a(NBTab.dbz), (String)"celula_legs", null);
        celula_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "celula").func_77655_b("celula_boots").func_77637_a(NBTab.dbz), (String)"celula_boots", null);
        daiz_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "daiz").func_77655_b("daiz_chest").func_77637_a(NBTab.dbz), (String)"daiz_chest", null);
        daiz_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "daiz").func_77655_b("daiz_boots").func_77637_a(NBTab.dbz), (String)"daiz_boots", null);
        dengoku_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "dengoku").func_77655_b("dengoku_chest").func_77637_a(NBTab.dbz), (String)"dengoku_chest", null);
        dgoku_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "dgoku").func_77655_b("dgoku_chest").func_77637_a(NBTab.dbz), (String)"dgoku_chest", null);
        dgoku_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "dgoku").func_77655_b("dgoku_legs").func_77637_a(NBTab.dbz), (String)"dgoku_legs", null);
        dgoku_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "dgoku").func_77655_b("dgoku_boots").func_77637_a(NBTab.dbz), (String)"dgoku_boots", null);
        dgokuss_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "dgokuss").func_77655_b("dgokuss_chest").func_77637_a(NBTab.dbz), (String)"dgokuss_chest", null);
        dgokuss_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "dgokuss").func_77655_b("dgokuss_legs").func_77637_a(NBTab.dbz), (String)"dgokuss_legs", null);
        dvegetabuu_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "dvegetabuu").func_77655_b("dvegetabuu_chest").func_77637_a(NBTab.dbz), (String)"dvegetabuu_chest", null);
        dvegetabuu_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "dvegetabuu").func_77655_b("dvegetabuu_legs").func_77637_a(NBTab.dbz), (String)"dvegetabuu_legs", null);
        dvegetabuu_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "dvegetabuu").func_77655_b("dvegetabuu_boots").func_77637_a(NBTab.dbz), (String)"dvegetabuu_boots", null);
        dvegetaf_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "dvegetaf").func_77655_b("dvegetaf_chest").func_77637_a(NBTab.dbz), (String)"dvegetaf_chest", null);
        dvegetaf_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "dvegetaf").func_77655_b("dvegetaf_legs").func_77637_a(NBTab.dbz), (String)"dvegetaf_legs", null);
        dvegetaf_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "dvegetaf").func_77655_b("dvegetaf_boots").func_77637_a(NBTab.dbz), (String)"dvegetaf_boots", null);
        dvegetas_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "dvegetas").func_77655_b("dvegetas_chest").func_77637_a(NBTab.dbz), (String)"dvegetas_chest", null);
        dvegetas_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "dvegetas").func_77655_b("dvegetas_legs").func_77637_a(NBTab.dbz), (String)"dvegetas_legs", null);
        dvegetas_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "dvegetas").func_77655_b("dvegetas_boots").func_77637_a(NBTab.dbz), (String)"dvegetas_boots", null);
        freeza_head = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 0, "freeza").func_77655_b("freeza_head").func_77637_a(NBTab.dbz), (String)"freeza_head", null);
        freeza_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "freeza").func_77655_b("freeza_chest").func_77637_a(NBTab.dbz), (String)"freeza_chest", null);
        freeza_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "freeza").func_77655_b("freeza_legs").func_77637_a(NBTab.dbz), (String)"freeza_legs", null);
        freeza_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "freeza").func_77655_b("freeza_boots").func_77637_a(NBTab.dbz), (String)"freeza_boots", null);
        freeza1_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "freeza1").func_77655_b("freeza1_chest").func_77637_a(NBTab.dbz), (String)"freeza1_chest", null);
        ginyuf0_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "ginyuf0").func_77655_b("ginyuf0_chest").func_77637_a(NBTab.dbz), (String)"ginyuf0_chest", null);
        ginyuf0_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "ginyuf0").func_77655_b("ginyuf0_legs").func_77637_a(NBTab.dbz), (String)"ginyuf0_legs", null);
        ginyuf0_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "ginyuf0").func_77655_b("ginyuf0_boots").func_77637_a(NBTab.dbz), (String)"ginyuf0_boots", null);
        ginyuf1_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "ginyuf1").func_77655_b("ginyuf1_chest").func_77637_a(NBTab.dbz), (String)"ginyuf1_chest", null);
        ginyuf1_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "ginyuf1").func_77655_b("ginyuf1_boots").func_77637_a(NBTab.dbz), (String)"ginyuf1_boots", null);
        gohankai_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "gohankai").func_77655_b("gohankai_chest").func_77637_a(NBTab.dbz), (String)"gohankai_chest", null);
        gohankai_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "gohankai").func_77655_b("gohankai_legs").func_77637_a(NBTab.dbz), (String)"gohankai_legs", null);
        gohankai_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "gohankai").func_77655_b("gohankai_boots").func_77637_a(NBTab.dbz), (String)"gohankai_boots", null);
        gohanwest_head = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 0, "gohanwest").func_77655_b("gohanwest_head").func_77637_a(NBTab.dbz), (String)"gohanwest_head", null);
        gohanwest_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "gohanwest").func_77655_b("gohanwest_chest").func_77637_a(NBTab.dbz), (String)"gohanwest_chest", null);
        gohanwest_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "gohanwest").func_77655_b("gohanwest_legs").func_77637_a(NBTab.dbz), (String)"gohanwest_legs", null);
        gohanwest_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "gohanwest").func_77655_b("gohanwest_boots").func_77637_a(NBTab.dbz), (String)"gohanwest_boots", null);
        gokueoz_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "gokueoz").func_77655_b("gokueoz_chest").func_77637_a(NBTab.dbz), (String)"gokueoz_chest", null);
        gokueoz_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "gokueoz").func_77655_b("gokueoz_legs").func_77637_a(NBTab.dbz), (String)"gokueoz_legs", null);
        gokueoz_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "gokueoz").func_77655_b("gokueoz_boots").func_77637_a(NBTab.dbz), (String)"gokueoz_boots", null);
        gokugo_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "gokugo").func_77655_b("gokugo_chest").func_77637_a(NBTab.dbz), (String)"gokugo_chest", null);
        gokugo_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "gokugo").func_77655_b("gokugo_legs").func_77637_a(NBTab.dbz), (String)"gokugo_legs", null);
        gokugo_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "gokugo").func_77655_b("gokugo_boots").func_77637_a(NBTab.dbz), (String)"gokugo_boots", null);
        gokujacket_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "gokujacket").func_77655_b("gokujacket_chest").func_77637_a(NBTab.dbz), (String)"gokujacket_chest", null);
        gokujacket_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "gokujacket").func_77655_b("gokujacket_legs").func_77637_a(NBTab.dbz), (String)"gokujacket_legs", null);
        gokujacket_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "gokujacket").func_77655_b("gokujacket_boots").func_77637_a(NBTab.dbz), (String)"gokujacket_boots", null);
        gokuss_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "gokuss").func_77655_b("gokuss_chest").func_77637_a(NBTab.dbz), (String)"gokuss_chest", null);
        gokuss_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "gokuss").func_77655_b("gokuss_legs").func_77637_a(NBTab.dbz), (String)"gokuss_legs", null);
        gokuss_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "gokuss").func_77655_b("gokuss_boots").func_77637_a(NBTab.dbz), (String)"gokuss_boots", null);
        gokuteen_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "gokuteen").func_77655_b("gokuteen_chest").func_77637_a(NBTab.dbz), (String)"gokuteen_chest", null);
        gokuteen_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "gokuteen").func_77655_b("gokuteen_legs").func_77637_a(NBTab.dbz), (String)"gokuteen_legs", null);
        gokuteen_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "gokuteen").func_77655_b("gokuteen_boots").func_77637_a(NBTab.dbz), (String)"gokuteen_boots", null);
        gokuy_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "gokuy").func_77655_b("gokuy_chest").func_77637_a(NBTab.dbz), (String)"gokuy_chest", null);
        gsoldier_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "gsoldier").func_77655_b("gsoldier_boots").func_77637_a(NBTab.dbz), (String)"gsoldier_boots", null);
        janemba_head = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 0, "janemba").func_77655_b("janemba_head").func_77637_a(NBTab.dbz), (String)"janemba_head", null);
        janemba1_head = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 0, "janemba1").func_77655_b("janemba1_head").func_77637_a(NBTab.dbz), (String)"janemba1_head", null);
        janemba_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "janemba").func_77655_b("janemba_chest").func_77637_a(NBTab.dbz), (String)"janemba_chest", null);
        janemba1_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "janemba1").func_77655_b("janemba1_chest").func_77637_a(NBTab.dbz), (String)"janemba1_chest", null);
        janemba_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "janemba").func_77655_b("janemba_legs").func_77637_a(NBTab.dbz), (String)"janemba_legs", null);
        janemba_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "janemba").func_77655_b("janemba_boots").func_77637_a(NBTab.dbz), (String)"janemba_boots", null);
        kcold_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "kcold").func_77655_b("kcold_chest").func_77637_a(NBTab.dbz), (String)"kcold_chest", null);
        kogu_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "kogu").func_77655_b("kogu_chest").func_77637_a(NBTab.dbz), (String)"kogu_chest", null);
        kogu_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "kogu").func_77655_b("kogu_legs").func_77637_a(NBTab.dbz), (String)"kogu_legs", null);
        kvegetaz_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "kvegetaz").func_77655_b("kvegetaz_chest").func_77637_a(NBTab.dbz), (String)"kvegetaz_chest", null);
        kvegetaz_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "kvegetaz").func_77655_b("kvegetaz_legs").func_77637_a(NBTab.dbz), (String)"kvegetaz_legs", null);
        kvegetaz_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "kvegetaz").func_77655_b("kvegetaz_boots").func_77637_a(NBTab.dbz), (String)"kvegetaz_boots", null);
        mfrieza_head = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 0, "mfrieza").func_77655_b("mfrieza_head").func_77637_a(NBTab.dbz), (String)"mfrieza_head", null);
        mfrieza_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "mfrieza").func_77655_b("mfrieza_chest").func_77637_a(NBTab.dbz), (String)"mfrieza_chest", null);
        mfrieza_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "mfrieza").func_77655_b("mfrieza_legs").func_77637_a(NBTab.dbz), (String)"mfrieza_legs", null);
        mfrieza_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "mfrieza").func_77655_b("mfrieza_boots").func_77637_a(NBTab.dbz), (String)"mfrieza_boots", null);
        mightymask_head = GameRegistry.registerItem((Item)new ArmorNB2(ArmorNB.NBmaterial, 1, 0, "mightymask").func_77655_b("mightymask_head").func_77637_a(NBTab.dbz), (String)"mightymask_head", null);
        mightymask_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "mightymask").func_77655_b("mightymask_chest").func_77637_a(NBTab.dbz), (String)"mightymask_chest", null);
        mightymask_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "mightymask").func_77655_b("mightymask_legs").func_77637_a(NBTab.dbz), (String)"mightymask_legs", null);
        mightymask_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "mightymask").func_77655_b("mightymask_boots").func_77637_a(NBTab.dbz), (String)"mightymask_boots", null);
        nail_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "nail").func_77655_b("nail_chest").func_77637_a(NBTab.dbz), (String)"nail_chest", null);
        nail_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "nail").func_77655_b("nail_legs").func_77637_a(NBTab.dbz), (String)"nail_legs", null);
        nail_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "nail").func_77655_b("nail_boots").func_77637_a(NBTab.dbz), (String)"nail_boots", null);
        olivue_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "olivue").func_77655_b("olivue_chest").func_77637_a(NBTab.dbz), (String)"olivue_chest", null);
        olivue_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "olivue").func_77655_b("olivue_legs").func_77637_a(NBTab.dbz), (String)"olivue_legs", null);
        olivue_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "olivue").func_77655_b("olivue_boots").func_77637_a(NBTab.dbz), (String)"olivue_boots", null);
        pikkon_head = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 0, "pikkon").func_77655_b("pikkon_head").func_77637_a(NBTab.dbz), (String)"pikkon_head", null);
        pikkon_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "pikkon").func_77655_b("pikkon_chest").func_77637_a(NBTab.dbz), (String)"pikkon_chest", null);
        pikkon_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "pikkon").func_77655_b("pikkon_legs").func_77637_a(NBTab.dbz), (String)"pikkon_legs", null);
        pikkon_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "pikkon").func_77655_b("pikkon_boots").func_77637_a(NBTab.dbz), (String)"pikkon_boots", null);
        postboy_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "postboy").func_77655_b("postboy_chest").func_77637_a(NBTab.dbz), (String)"postboy_chest", null);
        postboy_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "postboy").func_77655_b("postboy_legs").func_77637_a(NBTab.dbz), (String)"postboy_legs", null);
        postboy_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "postboy").func_77655_b("postboy_boots").func_77637_a(NBTab.dbz), (String)"postboy_boots", null);
        raditz_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "raditz").func_77655_b("raditz_chest").func_77637_a(NBTab.dbz), (String)"raditz_chest", null);
        raditz_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "raditz").func_77655_b("raditz_boots").func_77637_a(NBTab.dbz), (String)"raditz_boots", null);
        ryl_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "ryl").func_77655_b("ryl_chest").func_77637_a(NBTab.dbz), (String)"ryl_chest", null);
        ryl_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "ryl").func_77655_b("ryl_legs").func_77637_a(NBTab.dbz), (String)"ryl_legs", null);
        ryl_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "ryl").func_77655_b("ryl_boots").func_77637_a(NBTab.dbz), (String)"ryl_boots", null);
        saiyagirl_head = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 0, "saiyagirl").func_77655_b("saiyagirl_head").func_77637_a(NBTab.dbz), (String)"saiyagirl_head", null);
        saiyagirl_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "saiyagirl").func_77655_b("saiyagirl_chest").func_77637_a(NBTab.dbz), (String)"saiyagirl_chest", null);
        saiyagirl_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "saiyagirl").func_77655_b("saiyagirl_legs").func_77637_a(NBTab.dbz), (String)"saiyagirl_legs", null);
        saiyagirl_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "saiyagirl").func_77655_b("saiyagirl_boots").func_77637_a(NBTab.dbz), (String)"saiyagirl_boots", null);
        saiyan_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "saiyan").func_77655_b("saiyan_chest").func_77637_a(NBTab.dbz), (String)"saiyan_chest", null);
        saiyan_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "saiyan").func_77655_b("saiyan_legs").func_77637_a(NBTab.dbz), (String)"saiyan_legs", null);
        saiyan_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "saiyan").func_77655_b("saiyan_boots").func_77637_a(NBTab.dbz), (String)"saiyan_boots", null);
        salza_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "salza").func_77655_b("salza_chest").func_77637_a(NBTab.dbz), (String)"salza_chest", null);
        salza_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "salza").func_77655_b("salza_legs").func_77637_a(NBTab.dbz), (String)"salza_legs", null);
        salza_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "salza").func_77655_b("salza_boots").func_77637_a(NBTab.dbz), (String)"salza_boots", null);
        selypar_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "selypar").func_77655_b("selypar_chest").func_77637_a(NBTab.dbz), (String)"selypar_chest", null);
        selypar_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "selypar").func_77655_b("selypar_legs").func_77637_a(NBTab.dbz), (String)"selypar_legs", null);
        selypar_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "selypar").func_77655_b("selypar_boots").func_77637_a(NBTab.dbz), (String)"selypar_boots", null);
        tapion_head = GameRegistry.registerItem((Item)new ItemHeadNB("tapion", "3").func_77655_b("tapion_head").func_77637_a(NBTab.exvani), (String)"tapion_head", null);
        tapion_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "tapion").func_77655_b("tapion_chest").func_77637_a(NBTab.dbz), (String)"tapion_chest", null);
        tapion_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "tapion").func_77655_b("tapion_legs").func_77637_a(NBTab.dbz), (String)"tapion_legs", null);
        tapion_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "tapion").func_77655_b("tapion_boots").func_77637_a(NBTab.dbz), (String)"tapion_boots", null);
        trunksdbz_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "trunksdbz").func_77655_b("trunksdbz_chest").func_77637_a(NBTab.dbz), (String)"trunksdbz_chest", null);
        trunksdbz_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "trunksdbz").func_77655_b("trunksdbz_legs").func_77637_a(NBTab.dbz), (String)"trunksdbz_legs", null);
        trunksdbz_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "trunksdbz").func_77655_b("trunksdbz_boots").func_77637_a(NBTab.dbz), (String)"trunksdbz_boots", null);
        trunksdbzf_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "trunksdbzf").func_77655_b("trunksdbzf_chest").func_77637_a(NBTab.dbz), (String)"trunksdbzf_chest", null);
        trunksdbzf_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "trunksdbzf").func_77655_b("trunksdbzf_legs").func_77637_a(NBTab.dbz), (String)"trunksdbzf_legs", null);
        trunksdbzf_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "trunksdbzf").func_77655_b("trunksdbzf_boots").func_77637_a(NBTab.dbz), (String)"trunksdbzf_boots", null);
        trunksfjacket = GameRegistry.registerItem((Item)new MarksNB(0xFFFFFF, ArmorNB.NBmaterial, 1, "trunksfjacket", -1).func_77655_b("trunksfjacket").func_77637_a(NBTab.dbz), (String)"trunksfjacket", null);
        trunksfwaistcoat = GameRegistry.registerItem((Item)new MarksNB(0xFFFFFF, ArmorNB.NBmaterial, 1, "trunksfwaistcoat", -1).func_77655_b("trunksfwaistcoat").func_77637_a(NBTab.dbz), (String)"trunksfwaistcoat", null);
        trunksf_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "trunksf").func_77655_b("trunksf_chest").func_77637_a(NBTab.dbz), (String)"trunksf_chest", null);
        trunksf_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "trunksf").func_77655_b("trunksf_legs").func_77637_a(NBTab.dbz), (String)"trunksf_legs", null);
        trunksf_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "trunksf").func_77655_b("trunksf_boots").func_77637_a(NBTab.dbz), (String)"trunksf_boots", null);
        trunkspre_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "trunkspre").func_77655_b("trunkspre_chest").func_77637_a(NBTab.dbz), (String)"trunkspre_chest", null);
        trunkspre_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "trunkspre").func_77655_b("trunkspre_legs").func_77637_a(NBTab.dbz), (String)"trunkspre_legs", null);
        trunkspre_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "trunkspre").func_77655_b("trunkspre_boots").func_77637_a(NBTab.dbz), (String)"trunkspre_boots", null);
        tsufuru_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "tsufuru").func_77655_b("tsufuru_chest").func_77637_a(NBTab.dbz), (String)"tsufuru_chest", null);
        tsufuru_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "tsufuru").func_77655_b("tsufuru_legs").func_77637_a(NBTab.dbz), (String)"tsufuru_legs", null);
        tsufuru_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "tsufuru").func_77655_b("tsufuru_boots").func_77637_a(NBTab.dbz), (String)"tsufuru_boots", null);
        turles_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "turles").func_77655_b("turles_chest").func_77637_a(NBTab.dbz), (String)"turles_chest", null);
        turles_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "turles").func_77655_b("turles_boots").func_77637_a(NBTab.dbz), (String)"turles_boots", null);
        vegetabuu_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "vegetabuu").func_77655_b("vegetabuu_chest").func_77637_a(NBTab.dbz), (String)"vegetabuu_chest", null);
        vegetabuu_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "vegetabuu").func_77655_b("vegetabuu_legs").func_77637_a(NBTab.dbz), (String)"vegetabuu_legs", null);
        vegetabuu_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "vegetabuu").func_77655_b("vegetabuu_boots").func_77637_a(NBTab.dbz), (String)"vegetabuu_boots", null);
        vegetacs_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "vegetacs").func_77655_b("vegetacs_chest").func_77637_a(NBTab.dbz), (String)"vegetacs_chest", null);
        vegetacs_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "vegetacs").func_77655_b("vegetacs_legs").func_77637_a(NBTab.dbz), (String)"vegetacs_legs", null);
        vegetacs_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "vegetacs").func_77655_b("vegetacs_boots").func_77637_a(NBTab.dbz), (String)"vegetacs_boots", null);
        vegetaeoz_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "vegetaeoz").func_77655_b("vegetaeoz_chest").func_77637_a(NBTab.dbz), (String)"vegetaeoz_chest", null);
        vegetaeoz_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "vegetaeoz").func_77655_b("vegetaeoz_legs").func_77637_a(NBTab.dbz), (String)"vegetaeoz_legs", null);
        vegetaeoz_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "vegetaeoz").func_77655_b("vegetaeoz_boots").func_77637_a(NBTab.dbz), (String)"vegetaeoz_boots", null);
        vegetafr_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "vegetafr").func_77655_b("vegetafr_chest").func_77637_a(NBTab.dbz), (String)"vegetafr_chest", null);
        vegetafr_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "vegetafr").func_77655_b("vegetafr_legs").func_77637_a(NBTab.dbz), (String)"vegetafr_legs", null);
        vegetafr_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "vegetafr").func_77655_b("vegetafr_boots").func_77637_a(NBTab.dbz), (String)"vegetafr_boots", null);
        vegetasc_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "vegetasc").func_77655_b("vegetasc_chest").func_77637_a(NBTab.dbz), (String)"vegetasc_chest", null);
        vegetasc_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "vegetasc").func_77655_b("vegetasc_legs").func_77637_a(NBTab.dbz), (String)"vegetasc_legs", null);
        vegetasc_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "vegetasc").func_77655_b("vegetasc_boots").func_77637_a(NBTab.dbz), (String)"vegetasc_boots", null);
        vegetasca_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "vegetasca").func_77655_b("vegetasca_chest").func_77637_a(NBTab.dbz), (String)"vegetasca_chest", null);
        vegetasca_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "vegetasca").func_77655_b("vegetasca_legs").func_77637_a(NBTab.dbz), (String)"vegetasca_legs", null);
        vegetasca_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "vegetasca").func_77655_b("vegetasca_boots").func_77637_a(NBTab.dbz), (String)"vegetasca_boots", null);
        zangya_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "zangya").func_77655_b("zangya_chest").func_77637_a(NBTab.dbz), (String)"zangya_chest", null);
        zangya_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "zangya").func_77655_b("zangya_legs").func_77637_a(NBTab.dbz), (String)"zangya_legs", null);
    }
}

