/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  cpw.mods.fml.common.registry.GameRegistry
 *  net.minecraft.item.Item
 */
package me.NBArmors.armors;

import cpw.mods.fml.common.registry.GameRegistry;
import me.NBArmors.armors.ArmorNB;
import me.NBArmors.armors.ArmorNB2;
import me.NBArmors.armors.MarksNB;
import me.NBArmors.tabs.NBTab;
import net.minecraft.item.Item;

public class origin {
    public static Item baezel_chest;
    public static Item baezel_legs;
    public static Item baezel_boots;
    public static Item bardock21_chest;
    public static Item bardock21_legs;
    public static Item bardock21_boots;
    public static Item bulchi_chest;
    public static Item bulchi_legs;
    public static Item bulchi_boots;
    public static Item brolyb_chest;
    public static Item brolyb_legs;
    public static Item brolyb_boots;
    public static Item brolysa_chest;
    public static Item brolysa_legs;
    public static Item brolysa_boots;
    public static Item cauliflas_chest;
    public static Item cauliflas_legs;
    public static Item cauliflas_boots;
    public static Item crimson_chest;
    public static Item crimson_legs;
    public static Item crimson_boots;
    public static Item crimson0_chest;
    public static Item crimson0_legs;
    public static Item crimson0_boots;
    public static Item crimson1_chest;
    public static Item crimson1_legs;
    public static Item crimson1_boots;
    public static Item exarmor0_chest;
    public static Item exarmor0_legs;
    public static Item exarmor0_boots;
    public static Item exarmor1_chest;
    public static Item exarmor1_legs;
    public static Item exarmor1_boots;
    public static Item fsaiyan_chest;
    public static Item fsaiyan_legs;
    public static Item fsaiyan_boots;
    public static Item gifemale_chest;
    public static Item gifemale_legs;
    public static Item gifemale_boots;
    public static Item gine0_chest;
    public static Item gine0_legs;
    public static Item gine0_boots;
    public static Item gohanab_legs;
    public static Item gohanad_chest;
    public static Item gohanab_boots;
    public static Item gokuabsalon_chest;
    public static Item gokuabsalon_legs;
    public static Item gokuabsalon_boots;
    public static Item gokuaf_chest;
    public static Item gokuaf_legs;
    public static Item gokuaf_boots;
    public static Item gokujr_chest;
    public static Item gokujr_legs;
    public static Item gokujr_boots;
    public static Item gokutale_chest;
    public static Item gokutale_legs;
    public static Item gokutale_boots;
    public static Item gotenab_chest;
    public static Item gotenab_legs;
    public static Item gotenab_boots;
    public static Item ika_chest;
    public static Item ika_legs;
    public static Item ika_boots;
    public static Item kales_chest;
    public static Item kales_legs;
    public static Item kales_boots;
    public static Item maidk;
    public static Item maid_chest;
    public static Item maid_legs;
    public static Item maid_boots;
    public static Item matto_chest;
    public static Item matto_legs;
    public static Item matto_boots;
    public static Item nappie_chest;
    public static Item nappie_legs;
    public static Item nappie_boots;
    public static Item naruke_chest;
    public static Item naruke_legs;
    public static Item naruke_boots;
    public static Item okara_chest;
    public static Item okara_legs;
    public static Item okara_boots;
    public static Item okara0_chest;
    public static Item okara0_legs;
    public static Item okara0_boots;
    public static Item omnigokujacket;
    public static Item omnigoku_chest;
    public static Item omnigoku_legs;
    public static Item omnigoku_boots;
    public static Item panab_chest;
    public static Item panab_legs;
    public static Item panab_boots;
    public static Item prueba_head;
    public static Item prueba_chest;
    public static Item prueba_legs;
    public static Item prueba_boots;
    public static Item radichio_chest;
    public static Item radichio_legs;
    public static Item radichio_boots;
    public static Item radish_chest;
    public static Item radish_legs;
    public static Item radish_boots;
    public static Item saiyanq_chest;
    public static Item saiyanq_legs;
    public static Item saiyanq_boots;
    public static Item sasira_chest;
    public static Item sasira_legs;
    public static Item sasira_boots;
    public static Item sc18jacket;
    public static Item sc18_chest;
    public static Item sc18_legs;
    public static Item sc18_boots;
    public static Item supreme_chest;
    public static Item supreme0_chest;
    public static Item supreme1_chest;
    public static Item tienkai_chest;
    public static Item tienkai_legs;
    public static Item tienkai_boots;
    public static Item vegena_chest;
    public static Item vegena_legs;
    public static Item vegena_boots;
    public static Item vegetaab_chest;
    public static Item vegetaab_legs;
    public static Item vegetaab_boots;
    public static Item vegetatale_chest;
    public static Item vegetatale_legs;
    public static Item vegetatale_boots;
    public static Item vegitogt_chest;
    public static Item vegitogt_legs;
    public static Item vegitogt_boots;
    public static Item xicor_chest;
    public static Item xicor_legs;
    public static Item xicor_boots;
    public static Item yamoshi_chest;
    public static Item yamoshi0_chest;
    public static Item yamoshi_legs;
    public static Item yamoshi_boots;
    public static Item zarama_head;
    public static Item zarama_chest;
    public static Item zarama_legs;
    public static Item zarama_boots;

    public static void mainRegistry() {
        origin.initiliseItem();
        origin.registerItem();
    }

    public static void initiliseItem() {
    }

    public static void registerItem() {
        baezel_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "baezel").func_77655_b("baezel_chest").func_77637_a(NBTab.origin), (String)"baezel_chest", null);
        baezel_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "baezel").func_77655_b("baezel_legs").func_77637_a(NBTab.origin), (String)"baezel_legs", null);
        baezel_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "baezel").func_77655_b("baezel_boots").func_77637_a(NBTab.origin), (String)"baezel_boots", null);
        bardock21_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "bardock21").func_77655_b("bardock21_chest").func_77637_a(NBTab.origin), (String)"bardock21_chest", null);
        bardock21_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "bardock21").func_77655_b("bardock21_legs").func_77637_a(NBTab.origin), (String)"bardock21_legs", null);
        bardock21_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "bardock21").func_77655_b("bardock21_boots").func_77637_a(NBTab.origin), (String)"bardock21_boots", null);
        bulchi_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "bulchi").func_77655_b("bulchi_chest").func_77637_a(NBTab.origin), (String)"bulchi_chest", null);
        bulchi_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "bulchi").func_77655_b("bulchi_legs").func_77637_a(NBTab.origin), (String)"bulchi_legs", null);
        bulchi_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "bulchi").func_77655_b("bulchi_boots").func_77637_a(NBTab.origin), (String)"bulchi_boots", null);
        brolyb_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "brolyb").func_77655_b("brolyb_chest").func_77637_a(NBTab.origin), (String)"brolyb_chest", null);
        brolyb_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "brolyb").func_77655_b("brolyb_legs").func_77637_a(NBTab.origin), (String)"brolyb_legs", null);
        brolyb_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "brolyb").func_77655_b("brolyb_boots").func_77637_a(NBTab.origin), (String)"brolyb_boots", null);
        brolysa_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "brolysa").func_77655_b("brolysa_chest").func_77637_a(NBTab.origin), (String)"brolysa_chest", null);
        brolysa_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "brolysa").func_77655_b("brolysa_legs").func_77637_a(NBTab.origin), (String)"brolysa_legs", null);
        brolysa_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "brolysa").func_77655_b("brolysa_boots").func_77637_a(NBTab.origin), (String)"brolysa_boots", null);
        cauliflas_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "cauliflas").func_77655_b("cauliflas_chest").func_77637_a(NBTab.origin), (String)"cauliflas_chest", null);
        cauliflas_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "cauliflas").func_77655_b("cauliflas_legs").func_77637_a(NBTab.origin), (String)"cauliflas_legs", null);
        cauliflas_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "cauliflas").func_77655_b("cauliflas_boots").func_77637_a(NBTab.origin), (String)"cauliflas_boots", null);
        crimson_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "crimson").func_77655_b("crimson_chest").func_77637_a(NBTab.origin), (String)"crimson_chest", null);
        crimson_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "crimson").func_77655_b("crimson_legs").func_77637_a(NBTab.origin), (String)"crimson_legs", null);
        crimson_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "crimson").func_77655_b("crimson_boots").func_77637_a(NBTab.origin), (String)"crimson_boots", null);
        crimson0_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "crimson0").func_77655_b("crimson0_chest").func_77637_a(NBTab.origin), (String)"crimson0_chest", null);
        crimson0_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "crimson0").func_77655_b("crimson0_legs").func_77637_a(NBTab.origin), (String)"crimson0_legs", null);
        crimson0_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "crimson0").func_77655_b("crimson0_boots").func_77637_a(NBTab.origin), (String)"crimson0_boots", null);
        crimson1_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "crimson1").func_77655_b("crimson1_chest").func_77637_a(NBTab.origin), (String)"crimson1_chest", null);
        crimson1_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "crimson1").func_77655_b("crimson1_legs").func_77637_a(NBTab.origin), (String)"crimson1_legs", null);
        crimson1_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "crimson1").func_77655_b("crimson1_boots").func_77637_a(NBTab.origin), (String)"crimson1_boots", null);
        exarmor0_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "exarmor0").func_77655_b("exarmor0_chest").func_77637_a(NBTab.origin), (String)"exarmor0_chest", null);
        exarmor0_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "exarmor0").func_77655_b("exarmor0_legs").func_77637_a(NBTab.origin), (String)"exarmor0_legs", null);
        exarmor0_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "exarmor0").func_77655_b("exarmor0_boots").func_77637_a(NBTab.origin), (String)"exarmor0_boots", null);
        exarmor1_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "exarmor1").func_77655_b("exarmor1_chest").func_77637_a(NBTab.origin), (String)"exarmor1_chest", null);
        exarmor1_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "exarmor1").func_77655_b("exarmor1_legs").func_77637_a(NBTab.origin), (String)"exarmor1_legs", null);
        exarmor1_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "exarmor1").func_77655_b("exarmor1_boots").func_77637_a(NBTab.origin), (String)"exarmor1_boots", null);
        fsaiyan_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "fsaiyan").func_77655_b("fsaiyan_chest").func_77637_a(NBTab.origin), (String)"fsaiyan_chest", null);
        fsaiyan_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "fsaiyan").func_77655_b("fsaiyan_legs").func_77637_a(NBTab.origin), (String)"fsaiyan_legs", null);
        fsaiyan_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "fsaiyan").func_77655_b("fsaiyan_boots").func_77637_a(NBTab.origin), (String)"fsaiyan_boots", null);
        gifemale_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "gifemale").func_77655_b("gifemale_chest").func_77637_a(NBTab.origin), (String)"gifemale_chest", null);
        gifemale_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "gifemale").func_77655_b("gifemale_legs").func_77637_a(NBTab.origin), (String)"gifemale_legs", null);
        gifemale_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "gifemale").func_77655_b("gifemale_boots").func_77637_a(NBTab.origin), (String)"gifemale_boots", null);
        gine0_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "gine0").func_77655_b("gine0_chest").func_77637_a(NBTab.origin), (String)"gine0_chest", null);
        gine0_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "gine0").func_77655_b("gine0_legs").func_77637_a(NBTab.origin), (String)"gine0_legs", null);
        gine0_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "gine0").func_77655_b("gine0_boots").func_77637_a(NBTab.origin), (String)"gine0_boots", null);
        gohanad_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "gohanab").func_77655_b("gohanab_chest").func_77637_a(NBTab.origin), (String)"gohanab_chest", null);
        gohanab_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "gohanab").func_77655_b("gohanab_legs").func_77637_a(NBTab.origin), (String)"gohanab_legs", null);
        gohanab_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "gohanab").func_77655_b("gohanab_boots").func_77637_a(NBTab.origin), (String)"gohanab_boots", null);
        gokuabsalon_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "gokuabsalon").func_77655_b("gokuabsalon_chest").func_77637_a(NBTab.origin), (String)"gokuabsalon_chest", null);
        gokuabsalon_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "gokuabsalon").func_77655_b("gokuabsalon_legs").func_77637_a(NBTab.origin), (String)"gokuabsalon_legs", null);
        gokuabsalon_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "gokuabsalon").func_77655_b("gokuabsalon_boots").func_77637_a(NBTab.origin), (String)"gokuabsalon_boots", null);
        gokuaf_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "gokuaf").func_77655_b("gokuaf_chest").func_77637_a(NBTab.origin), (String)"gokuaf_chest", null);
        gokuaf_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "gokuaf").func_77655_b("gokuaf_legs").func_77637_a(NBTab.origin), (String)"gokuaf_legs", null);
        gokuaf_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "gokuaf").func_77655_b("gokuaf_boots").func_77637_a(NBTab.origin), (String)"gokuaf_boots", null);
        gokujr_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "gokujr").func_77655_b("gokujr_chest").func_77637_a(NBTab.origin), (String)"gokujr_chest", null);
        gokujr_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "gokujr").func_77655_b("gokujr_legs").func_77637_a(NBTab.origin), (String)"gokujr_legs", null);
        gokujr_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "gokujr").func_77655_b("gokujr_boots").func_77637_a(NBTab.origin), (String)"gokujr_boots", null);
        gokutale_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "gokutale").func_77655_b("gokutale_chest").func_77637_a(NBTab.origin), (String)"gokutale_chest", null);
        gokutale_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "gokutale").func_77655_b("gokutale_legs").func_77637_a(NBTab.origin), (String)"gokutale_legs", null);
        gokutale_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "gokutale").func_77655_b("gokutale_boots").func_77637_a(NBTab.origin), (String)"gokutale_boots", null);
        gotenab_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "gotenab").func_77655_b("gotenab_chest").func_77637_a(NBTab.origin), (String)"gotenab_chest", null);
        gotenab_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "gotenab").func_77655_b("gotenab_legs").func_77637_a(NBTab.origin), (String)"gotenab_legs", null);
        gotenab_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "gotenab").func_77655_b("gotenab_boots").func_77637_a(NBTab.origin), (String)"gotenab_boots", null);
        ika_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "ika").func_77655_b("ika_chest").func_77637_a(NBTab.origin), (String)"ika_chest", null);
        ika_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "ika").func_77655_b("ika_legs").func_77637_a(NBTab.origin), (String)"ika_legs", null);
        ika_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "ika").func_77655_b("ika_boots").func_77637_a(NBTab.origin), (String)"ika_boots", null);
        kales_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "kales").func_77655_b("kales_chest").func_77637_a(NBTab.origin), (String)"kales_chest", null);
        kales_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "kales").func_77655_b("kales_legs").func_77637_a(NBTab.origin), (String)"kales_legs", null);
        kales_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "kales").func_77655_b("kales_boots").func_77637_a(NBTab.origin), (String)"kales_boots", null);
        maidk = GameRegistry.registerItem((Item)new MarksNB(0xFFFFFF, ArmorNB.NBmaterial, 0, "maidk", 8).func_77655_b("maidk").func_77637_a(NBTab.origin), (String)"maidk", null);
        maid_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "maid").func_77655_b("maid_chest").func_77637_a(NBTab.origin), (String)"maid_chest", null);
        maid_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "maid").func_77655_b("maid_legs").func_77637_a(NBTab.origin), (String)"maid_legs", null);
        maid_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "maid").func_77655_b("maid_boots").func_77637_a(NBTab.origin), (String)"maid_boots", null);
        matto_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "matto").func_77655_b("matto_chest").func_77637_a(NBTab.origin), (String)"matto_chest", null);
        matto_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "matto").func_77655_b("matto_legs").func_77637_a(NBTab.origin), (String)"matto_legs", null);
        matto_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "matto").func_77655_b("matto_boots").func_77637_a(NBTab.origin), (String)"matto_boots", null);
        nappie_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "nappie").func_77655_b("nappie_chest").func_77637_a(NBTab.origin), (String)"nappie_chest", null);
        nappie_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "nappie").func_77655_b("nappie_legs").func_77637_a(NBTab.origin), (String)"nappie_legs", null);
        nappie_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "nappie").func_77655_b("nappie_boots").func_77637_a(NBTab.origin), (String)"nappie_boots", null);
        naruke_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "naruke").func_77655_b("naruke_chest").func_77637_a(NBTab.origin), (String)"naruke_chest", null);
        naruke_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "naruke").func_77655_b("naruke_legs").func_77637_a(NBTab.origin), (String)"naruke_legs", null);
        naruke_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "naruke").func_77655_b("naruke_boots").func_77637_a(NBTab.origin), (String)"naruke_boots", null);
        okara_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "okara").func_77655_b("okara_chest").func_77637_a(NBTab.origin), (String)"okara_chest", null);
        okara_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "okara").func_77655_b("okara_legs").func_77637_a(NBTab.origin), (String)"okara_legs", null);
        okara_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "okara").func_77655_b("okara_boots").func_77637_a(NBTab.origin), (String)"okara_boots", null);
        okara0_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "okara0").func_77655_b("okara0_chest").func_77637_a(NBTab.origin), (String)"okara0_chest", null);
        okara0_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "okara0").func_77655_b("okara0_legs").func_77637_a(NBTab.origin), (String)"okara0_legs", null);
        okara0_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "okara0").func_77655_b("okara0_boots").func_77637_a(NBTab.origin), (String)"okara0_boots", null);
        omnigokujacket = GameRegistry.registerItem((Item)new MarksNB(0xFFFFFF, ArmorNB.NBmaterial, 1, "omnigokujacket", -1).func_77655_b("omnigokujacket").func_77637_a(NBTab.origin), (String)"omnigokujacket", null);
        omnigoku_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "omnigoku").func_77655_b("omnigoku_chest").func_77637_a(NBTab.origin), (String)"omnigoku_chest", null);
        omnigoku_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "omnigoku").func_77655_b("omnigoku_legs").func_77637_a(NBTab.origin), (String)"omnigoku_legs", null);
        omnigoku_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "omnigoku").func_77655_b("omnigoku_boots").func_77637_a(NBTab.origin), (String)"omnigoku_boots", null);
        panab_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "panab").func_77655_b("panab_chest").func_77637_a(NBTab.origin), (String)"panab_chest", null);
        panab_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "panab").func_77655_b("panab_legs").func_77637_a(NBTab.origin), (String)"panab_legs", null);
        panab_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "panab").func_77655_b("panab_boots").func_77637_a(NBTab.origin), (String)"panab_boots", null);
        radichio_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "radichio").func_77655_b("radichio_chest").func_77637_a(NBTab.origin), (String)"radichio_chest", null);
        radichio_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "radichio").func_77655_b("radichio_legs").func_77637_a(NBTab.origin), (String)"radichio_legs", null);
        radichio_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "radichio").func_77655_b("radichio_boots").func_77637_a(NBTab.origin), (String)"radichio_boots", null);
        radish_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "radish").func_77655_b("radish_chest").func_77637_a(NBTab.origin), (String)"radish_chest", null);
        radish_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "radish").func_77655_b("radish_legs").func_77637_a(NBTab.origin), (String)"radish_legs", null);
        radish_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "radish").func_77655_b("radish_boots").func_77637_a(NBTab.origin), (String)"radish_boots", null);
        saiyanq_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "saiyanq").func_77655_b("saiyanq_chest").func_77637_a(NBTab.origin), (String)"saiyanq_chest", null);
        saiyanq_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "saiyanq").func_77655_b("saiyanq_legs").func_77637_a(NBTab.origin), (String)"saiyanq_legs", null);
        saiyanq_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "saiyanq").func_77655_b("saiyanq_boots").func_77637_a(NBTab.origin), (String)"saiyanq_boots", null);
        sasira_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "sasira").func_77655_b("sasira_chest").func_77637_a(NBTab.origin), (String)"sasira_chest", null);
        sasira_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "sasira").func_77655_b("sasira_legs").func_77637_a(NBTab.origin), (String)"sasira_legs", null);
        sasira_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "sasira").func_77655_b("sasira_boots").func_77637_a(NBTab.origin), (String)"sasira_boots", null);
        sc18jacket = GameRegistry.registerItem((Item)new MarksNB(0xFFFFFF, ArmorNB.NBmaterial, 1, "sc18jacket", -1).func_77655_b("sc18jacket").func_77637_a(NBTab.exvani), (String)"sc18jacket", null);
        sc18_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "sc18").func_77655_b("sc18_chest").func_77637_a(NBTab.origin), (String)"sc18_chest", null);
        sc18_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "sc18").func_77655_b("sc18_legs").func_77637_a(NBTab.origin), (String)"sc18_legs", null);
        sc18_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "sc18").func_77655_b("sc18_boots").func_77637_a(NBTab.origin), (String)"sc18_boots", null);
        supreme_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "supreme").func_77655_b("supreme_chest").func_77637_a(NBTab.origin), (String)"supreme_chest", null);
        supreme0_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "supreme0").func_77655_b("supreme0_chest").func_77637_a(NBTab.origin), (String)"supreme0_chest", null);
        supreme1_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "supreme1").func_77655_b("supreme1_chest").func_77637_a(NBTab.origin), (String)"supreme1_chest", null);
        tienkai_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "tienkai").func_77655_b("tienkai_chest").func_77637_a(NBTab.origin), (String)"tienkai_chest", null);
        tienkai_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "tienkai").func_77655_b("tienkai_legs").func_77637_a(NBTab.origin), (String)"tienkai_legs", null);
        tienkai_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "tienkai").func_77655_b("tienkai_boots").func_77637_a(NBTab.origin), (String)"tienkai_boots", null);
        vegena_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "vegena").func_77655_b("vegena_chest").func_77637_a(NBTab.origin), (String)"vegena_chest", null);
        vegena_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "vegena").func_77655_b("vegena_legs").func_77637_a(NBTab.origin), (String)"vegena_legs", null);
        vegena_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "vegena").func_77655_b("vegena_boots").func_77637_a(NBTab.origin), (String)"vegena_boots", null);
        vegetaab_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "vegetaab").func_77655_b("vegetaab_chest").func_77637_a(NBTab.origin), (String)"vegetaab_chest", null);
        vegetaab_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "vegetaab").func_77655_b("vegetaab_legs").func_77637_a(NBTab.origin), (String)"vegetaab_legs", null);
        vegetaab_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "vegetaab").func_77655_b("vegetaab_boots").func_77637_a(NBTab.origin), (String)"vegetaab_boots", null);
        vegetatale_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "vegetatale").func_77655_b("vegetatale_chest").func_77637_a(NBTab.origin), (String)"vegetatale_chest", null);
        vegetatale_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "vegetatale").func_77655_b("vegetatale_legs").func_77637_a(NBTab.origin), (String)"vegetatale_legs", null);
        vegetatale_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "vegetatale").func_77655_b("vegetatale_boots").func_77637_a(NBTab.origin), (String)"vegetatale_boots", null);
        vegitogt_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "vegitogt").func_77655_b("vegitogt_chest").func_77637_a(NBTab.origin), (String)"vegitogt_chest", null);
        vegitogt_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "vegitogt").func_77655_b("vegitogt_legs").func_77637_a(NBTab.origin), (String)"vegitogt_legs", null);
        vegitogt_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "vegitogt").func_77655_b("vegitogt_boots").func_77637_a(NBTab.origin), (String)"vegitogt_boots", null);
        xicor_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "xicor").func_77655_b("xicor_chest").func_77637_a(NBTab.origin), (String)"xicor_chest", null);
        xicor_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "xicor").func_77655_b("xicor_legs").func_77637_a(NBTab.origin), (String)"xicor_legs", null);
        xicor_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "xicor").func_77655_b("xicor_boots").func_77637_a(NBTab.origin), (String)"xicor_boots", null);
        yamoshi_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "yamoshi").func_77655_b("yamoshi_chest").func_77637_a(NBTab.origin), (String)"yamoshi_chest", null);
        yamoshi0_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "yamoshi0").func_77655_b("yamoshi0_chest").func_77637_a(NBTab.origin), (String)"yamoshi0_chest", null);
        yamoshi_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "yamoshi").func_77655_b("yamoshi_legs").func_77637_a(NBTab.origin), (String)"yamoshi_legs", null);
        yamoshi_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "yamoshi").func_77655_b("yamoshi_boots").func_77637_a(NBTab.origin), (String)"yamoshi_boots", null);
        zarama_head = GameRegistry.registerItem((Item)new ArmorNB2(ArmorNB.NBmaterial, 1, 0, "zarama").func_77655_b("zarama_head").func_77637_a(NBTab.origin), (String)"zarama_head", null);
        zarama_chest = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 1, "zarama").func_77655_b("zarama_chest").func_77637_a(NBTab.origin), (String)"zarama_chest", null);
        zarama_legs = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 2, "zarama").func_77655_b("zarama_legs").func_77637_a(NBTab.origin), (String)"zarama_legs", null);
        zarama_boots = GameRegistry.registerItem((Item)new ArmorNB(ArmorNB.NBmaterial, 1, 3, "zarama").func_77655_b("zarama_boots").func_77637_a(NBTab.origin), (String)"zarama_boots", null);
    }
}

